# Generated by Django 5.2.16 on 2026-07-09 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='default_meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='default_meta_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='default_og_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='favicon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='google_maps_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='map_embed_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='primary_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='recipient_email',
            field=models.EmailField(blank=True, help_text='Internal recipient for contact form submissions. Not exposed publicly.', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='secondary_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediaasset'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='supported_languages',
            field=models.JSONField(blank=True, default=list, help_text='List of supported language codes, e.g. ["en", "ar"].'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='working_hours',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='x_url',
            field=models.URLField(blank=True, verbose_name='X (Twitter) URL'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only one active record is recommended. Activating this record deactivates others.'),
        ),
    ]
