# Generated by Django 6.0.2 on 2026-07-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_sitesetting_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='canonical_base_url',
            field=models.URLField(blank=True, help_text='Base URL for canonical links, e.g. https://sidrahsoft.com'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='default_og_description',
            field=models.TextField(blank=True, help_text='Open Graph description. Falls back to default meta description.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='default_og_title',
            field=models.CharField(blank=True, help_text='Open Graph title. Falls back to default meta title.', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='organization_description',
            field=models.TextField(blank=True, help_text='Description for Organization schema.org structured data.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='robots_index',
            field=models.BooleanField(default=True, help_text='Global toggle: allow search engines to index the site.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='twitter_card_type',
            field=models.CharField(default='summary_large_image', help_text='Twitter card type: summary, summary_large_image, or player.', max_length=30),
        ),
    ]
