# Generated by Django 5.2.17 on 2026-09-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_seo_management_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='meta_pixel_enabled',
            field=models.BooleanField(default=False, help_text='Enable Meta (Facebook) Pixel tracking on the public website.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='meta_pixel_id',
            field=models.CharField(blank=True, default='', help_text='Meta Pixel ID — numeric string only, e.g. 1541476880609183.', max_length=30),
        ),
    ]
