# Generated by Django 5.2.17 on 2026-09-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_meta_pixel_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='google_analytics_enabled',
            field=models.BooleanField(default=False, help_text='Enable Google Analytics 4. Stored for reference; not loaded directly unless explicitly chosen.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='google_analytics_measurement_id',
            field=models.CharField(blank=True, default='', help_text='GA4 Measurement ID, e.g. G-XXXXXXXXXX.', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='google_search_console_sitemap_url',
            field=models.CharField(blank=True, default='', help_text='Sitemap URL, e.g. /sitemap.xml or https://sidrahsoft.com/sitemap.xml', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='google_search_console_verification_method',
            field=models.CharField(blank=True, default='dns', help_text='Preferred verification method: dns, html_meta, or html_file. DNS is preferred.', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='google_search_console_verification_token',
            field=models.CharField(blank=True, default='', help_text='Optional HTML meta verification token. Only used if HTML meta verification is intentionally supported.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='google_tag_manager_container_id',
            field=models.CharField(blank=True, default='', help_text='GTM container ID, e.g. GTM-XXXXXXX.', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='google_tag_manager_enabled',
            field=models.BooleanField(default=False, help_text='Enable Google Tag Manager. Not loaded on the website until implementation is reviewed.'),
        ),
    ]
