# Generated by Django 6.0.2 on 2026-09-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_analytics_integrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='tiktok_url',
            field=models.URLField(blank=True, verbose_name='TikTok URL'),
        ),
    ]
