# Generated by Django 6.0.2 on 2026-09-09 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_media_asset_fields'),
        ('site_settings', '0006_tiktok_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_key', models.CharField(choices=[('home', 'Homepage'), ('ai_automation', 'AI Automation'), ('training', 'Training Listing'), ('careers', 'Careers'), ('case_studies', 'Case Studies Listing'), ('insights', 'Insights Listing'), ('certificate_verify', 'Certificate Verification')], help_text='Select a known public page. New routes cannot be created here.', max_length=50, unique=True)),
                ('seo_title_en', models.CharField(blank=True, max_length=120)),
                ('seo_title_ar', models.CharField(blank=True, max_length=120)),
                ('meta_description_en', models.TextField(blank=True)),
                ('meta_description_ar', models.TextField(blank=True)),
                ('og_title_en', models.CharField(blank=True, max_length=120)),
                ('og_title_ar', models.CharField(blank=True, max_length=120)),
                ('og_description_en', models.TextField(blank=True)),
                ('og_description_ar', models.TextField(blank=True)),
                ('robots_index', models.BooleanField(default=True, help_text='Allow search engines to index this page.')),
                ('robots_follow', models.BooleanField(default=True, help_text='Allow search engines to follow links on this page.')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediaasset')),
            ],
            options={
                'verbose_name': 'Static Page SEO',
                'verbose_name_plural': 'Static Page SEO',
                'db_table': 'site_settings_staticpageseo',
            },
        ),
    ]
