# Generated by Django 6.0.2 on 2026-09-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0008_alter_staticpageseo_page_key_remove_certificate_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpageseo',
            name='page_key',
            field=models.CharField(choices=[('home', 'Homepage'), ('ai_automation', 'AI Automation'), ('training', 'Training Listing'), ('training_offers', 'Training Offers'), ('careers', 'Careers'), ('case_studies', 'Case Studies Listing'), ('insights', 'Insights Listing')], help_text='Select a known public page. New routes cannot be created here.', max_length=50, unique=True),
        ),
    ]
