# Generated by Django 6.0.2 on 2026-09-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0009_training_offers_static_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='training_confirmation_cta_label_ar',
            field=models.CharField(blank=True, default='', help_text='Call-to-action button label (Arabic).', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='training_confirmation_cta_label_en',
            field=models.CharField(blank=True, default='', help_text='Call-to-action button label (English).', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='training_confirmation_cta_url',
            field=models.CharField(blank=True, default='', help_text='Call-to-action destination URL. Must be a safe internal path or https URL.', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='training_confirmation_email_enabled',
            field=models.BooleanField(default=True, help_text='Enable sending confirmation emails to applicants after successful training registration.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='training_confirmation_footer_ar',
            field=models.TextField(blank=True, default='', help_text='Footer/support copy shown below the main message (Arabic).'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='training_confirmation_footer_en',
            field=models.TextField(blank=True, default='', help_text='Footer/support copy shown below the main message (English).'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='training_confirmation_heading_ar',
            field=models.CharField(blank=True, default='', help_text='Heading shown at the top of the Arabic email body.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='training_confirmation_heading_en',
            field=models.CharField(blank=True, default='', help_text='Heading shown at the top of the English email body.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='training_confirmation_message_ar',
            field=models.TextField(blank=True, default='', help_text='Main confirmation message body (Arabic). Safe placeholders: {{applicant_name}}, {{program_name}}.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='training_confirmation_message_en',
            field=models.TextField(blank=True, default='', help_text='Main confirmation message body (English). Safe placeholders: {{applicant_name}}, {{program_name}}.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='training_confirmation_reply_to',
            field=models.EmailField(blank=True, default='sidrahsoft@gmail.com', help_text='Reply-To address for confirmation emails. Must be a monitored mailbox.', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='training_confirmation_sender_name',
            field=models.CharField(blank=True, default='Sidrah Soft', help_text='Display name shown in the From header. The authenticated sender address is infrastructure-controlled.', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='training_confirmation_subject_ar',
            field=models.CharField(blank=True, default='', help_text='Subject line for Arabic confirmation emails.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='training_confirmation_subject_en',
            field=models.CharField(blank=True, default='', help_text='Subject line for English confirmation emails.', max_length=200),
        ),
    ]
