# Generated by Django 6.0.2 on 2026-09-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0011_add_services_static_page_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='campaign_pricing_mode',
            field=models.BooleanField(default=True, help_text='When enabled, Professional course prices are hidden from public API responses and the frontend shows "pricing coming soon". Starter course prices (99 EGP) are always public. Set to False when campaign offers are finalized.'),
        ),
    ]
