# Generated by Django 6.0.2 on 2026-09-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0012_add_campaign_pricing_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='campaign_pricing_mode',
            field=models.BooleanField(default=True, help_text='When enabled, Professional course prices are hidden from public API responses and the frontend shows "pricing coming soon". Starter course prices (499 EGP) are always public. Set to False when campaign offers are finalized.'),
        ),
    ]
