# Generated by Django 5.2.16 on 2026-07-11 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(blank=True, help_text='Denormalized username for audit trail if user is deleted.', max_length=150)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('publish', 'Publish'), ('unpublish', 'Unpublish'), ('archive', 'Archive'), ('restore', 'Restore'), ('status_change', 'Status Change'), ('assign', 'Assign'), ('export', 'Export'), ('settings_change', 'Settings Change')], db_index=True, help_text='Type of activity performed.', max_length=32)),
                ('module', models.CharField(blank=True, choices=[('auth', 'Authentication'), ('dashboard', 'Dashboard'), ('site_settings', 'Site Settings'), ('navigation', 'Navigation'), ('partners', 'Partners'), ('services', 'Services'), ('case_studies', 'Case Studies'), ('careers', 'Careers'), ('insights', 'Insights'), ('contact', 'Contact'), ('media', 'Media'), ('users', 'Users'), ('activity_logs', 'Activity Logs')], db_index=True, help_text='CMS module the activity belongs to.', max_length=32)),
                ('object_type', models.CharField(blank=True, db_index=True, help_text='Django model label or content type, e.g. "services.Service".', max_length=100)),
                ('object_id', models.CharField(blank=True, db_index=True, help_text='Primary key or public identifier of the target object.', max_length=40)),
                ('object_repr', models.CharField(blank=True, help_text='Human-readable summary of the target object.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of the activity.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Structured, sanitized metadata. Never stores secrets.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address at the time of the activity.', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Client user-agent string (bounded during creation).')),
                ('origin', models.CharField(blank=True, help_text='Origin header of the request, if available.', max_length=255)),
                ('request_method', models.CharField(blank=True, help_text='HTTP method of the request that triggered the log.', max_length=10)),
                ('request_path', models.CharField(blank=True, db_index=True, help_text='URL path of the request that triggered the log.', max_length=255)),
                ('is_success', models.BooleanField(db_index=True, default=True, help_text='Whether the activity completed successfully.')),
                ('failure_reason', models.CharField(blank=True, help_text='Brief, safe failure reason when is_success is False.', max_length=255)),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'activity_logs_activitylog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='actlog_created_idx'), models.Index(fields=['user'], name='actlog_user_idx'), models.Index(fields=['action'], name='actlog_action_idx'), models.Index(fields=['module'], name='actlog_module_idx'), models.Index(fields=['is_success'], name='actlog_success_idx'), models.Index(fields=['object_type', 'object_id'], name='actlog_object_idx')],
            },
        ),
    ]
