# Generated by Django 5.2.16 on 2026-08-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='module',
            field=models.CharField(blank=True, choices=[('auth', 'Authentication'), ('dashboard', 'Dashboard'), ('site_settings', 'Site Settings'), ('navigation', 'Navigation'), ('partners', 'Partners'), ('services', 'Services'), ('case_studies', 'Case Studies'), ('careers', 'Careers'), ('insights', 'Insights'), ('contact', 'Contact'), ('media', 'Media'), ('users', 'Users'), ('activity_logs', 'Activity Logs'), ('training', 'Training')], db_index=True, help_text='CMS module the activity belongs to.', max_length=32),
        ),
    ]
