# Generated by Django 6.0.2 on 2026-08-28 03:00
# Consolidated: adds training_registrations + certificates module choices
# and issue + revoke action choices.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0002_alter_activitylog_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='module',
            field=models.CharField(
                blank=True,
                choices=[
                    ('auth', 'Authentication'),
                    ('dashboard', 'Dashboard'),
                    ('site_settings', 'Site Settings'),
                    ('navigation', 'Navigation'),
                    ('partners', 'Partners'),
                    ('services', 'Services'),
                    ('case_studies', 'Case Studies'),
                    ('careers', 'Careers'),
                    ('insights', 'Insights'),
                    ('contact', 'Contact'),
                    ('media', 'Media'),
                    ('users', 'Users'),
                    ('activity_logs', 'Activity Logs'),
                    ('training', 'Training'),
                    ('training_registrations', 'Training Registrations'),
                    ('certificates', 'Certificates'),
                ],
                db_index=True,
                help_text='CMS module the activity belongs to.',
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(
                choices=[
                    ('login', 'Login'),
                    ('logout', 'Logout'),
                    ('login_failed', 'Login Failed'),
                    ('create', 'Create'),
                    ('update', 'Update'),
                    ('delete', 'Delete'),
                    ('publish', 'Publish'),
                    ('unpublish', 'Unpublish'),
                    ('archive', 'Archive'),
                    ('restore', 'Restore'),
                    ('status_change', 'Status Change'),
                    ('assign', 'Assign'),
                    ('export', 'Export'),
                    ('settings_change', 'Settings Change'),
                    ('issue', 'Issue'),
                    ('revoke', 'Revoke'),
                ],
                db_index=True,
                help_text='Type of activity performed.',
                max_length=32,
            ),
        ),
    ]
