# Generated by Django 6.0.2 on 2026-09-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0003_training_module_and_action_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='module',
            field=models.CharField(blank=True, choices=[('auth', 'Authentication'), ('dashboard', 'Dashboard'), ('site_settings', 'Site Settings'), ('navigation', 'Navigation'), ('partners', 'Partners'), ('services', 'Services'), ('case_studies', 'Case Studies'), ('careers', 'Careers'), ('insights', 'Insights'), ('contact', 'Contact'), ('media', 'Media'), ('users', 'Users'), ('activity_logs', 'Activity Logs'), ('training', 'Training'), ('training_registrations', 'Training Registrations'), ('certificates', 'Certificates'), ('forms', 'Forms')], db_index=True, help_text='CMS module the activity belongs to.', max_length=32),
        ),
    ]
