# Generated by Django 5.2.16 on 2026-07-10 21:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_ar', models.CharField(blank=True, max_length=255, verbose_name='Title (Arabic)')),
                ('slug', models.SlugField(help_text='URL-safe identifier.', max_length=255, unique=True, verbose_name='Slug')),
                ('department_en', models.CharField(blank=True, max_length=120, verbose_name='Department (English)')),
                ('department_ar', models.CharField(blank=True, max_length=120, verbose_name='Department (Arabic)')),
                ('location_en', models.CharField(blank=True, max_length=120, verbose_name='Location (English)')),
                ('location_ar', models.CharField(blank=True, max_length=120, verbose_name='Location (Arabic)')),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship'), ('freelance', 'Freelance'), ('temporary', 'Temporary'), ('other', 'Other')], default='full_time', max_length=32, verbose_name='Employment type')),
                ('workplace_type', models.CharField(choices=[('onsite', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='hybrid', max_length=32, verbose_name='Workplace type')),
                ('experience_level', models.CharField(choices=[('entry', 'Entry-level'), ('junior', 'Junior'), ('mid', 'Mid-level'), ('senior', 'Senior'), ('lead', 'Lead'), ('manager', 'Manager'), ('unspecified', 'Unspecified')], default='unspecified', max_length=32, verbose_name='Experience level')),
                ('short_description_en', models.TextField(blank=True, verbose_name='Short description (English)')),
                ('short_description_ar', models.TextField(blank=True, verbose_name='Short description (Arabic)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (Arabic)')),
                ('responsibilities_en', models.TextField(blank=True, verbose_name='Responsibilities (English)')),
                ('responsibilities_ar', models.TextField(blank=True, verbose_name='Responsibilities (Arabic)')),
                ('requirements_en', models.TextField(blank=True, verbose_name='Requirements (English)')),
                ('requirements_ar', models.TextField(blank=True, verbose_name='Requirements (Arabic)')),
                ('preferred_qualifications_en', models.TextField(blank=True, verbose_name='Preferred qualifications (English)')),
                ('preferred_qualifications_ar', models.TextField(blank=True, verbose_name='Preferred qualifications (Arabic)')),
                ('benefits_en', models.TextField(blank=True, verbose_name='Benefits (English)')),
                ('benefits_ar', models.TextField(blank=True, verbose_name='Benefits (Arabic)')),
                ('application_method', models.CharField(choices=[('external_url', 'External URL'), ('email', 'Email'), ('contact_page', 'Contact page')], default='contact_page', max_length=32, verbose_name='Application method')),
                ('external_apply_url', models.URLField(blank=True, verbose_name='External apply URL')),
                ('application_email', models.EmailField(blank=True, max_length=254, verbose_name='Application email')),
                ('posted_date', models.DateField(default=django.utils.timezone.now, verbose_name='Posted date')),
                ('closing_date', models.DateField(blank=True, help_text='Leave blank for evergreen postings. Expired jobs are hidden from public APIs.', null=True, verbose_name='Closing date')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower values appear first.', verbose_name='Display order')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive jobs are hidden from public APIs.', verbose_name='Active')),
                ('show_on_homepage', models.BooleanField(default=False, verbose_name='Show on homepage')),
                ('seo_title_en', models.CharField(blank=True, max_length=255, verbose_name='SEO title (English)')),
                ('seo_title_ar', models.CharField(blank=True, max_length=255, verbose_name='SEO title (Arabic)')),
                ('seo_description_en', models.TextField(blank=True, verbose_name='SEO description (English)')),
                ('seo_description_ar', models.TextField(blank=True, verbose_name='SEO description (Arabic)')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'careers_job',
                'ordering': ['-is_featured', 'display_order', '-posted_date', 'title_en'],
                'indexes': [models.Index(fields=['is_active', 'show_on_homepage', 'display_order'], name='careers_active_homepage_idx'), models.Index(fields=['is_active', 'closing_date', 'posted_date'], name='careers_active_dates_idx')],
            },
        ),
    ]
