# Generated by Django 6.0.2 on 2026-09-09 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAutomationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_eyebrow_en', models.CharField(blank=True, max_length=80)),
                ('hero_eyebrow_ar', models.CharField(blank=True, max_length=80)),
                ('hero_title_en', models.CharField(blank=True, max_length=200)),
                ('hero_title_ar', models.CharField(blank=True, max_length=200)),
                ('hero_subtitle_en', models.TextField(blank=True)),
                ('hero_subtitle_ar', models.TextField(blank=True)),
                ('hero_cta_label_en', models.CharField(blank=True, max_length=60)),
                ('hero_cta_label_ar', models.CharField(blank=True, max_length=60)),
                ('hero_cta_destination', models.CharField(blank=True, help_text='Internal path (e.g. /#contact) or external URL.', max_length=255)),
                ('hero_secondary_cta_label_en', models.CharField(blank=True, max_length=60)),
                ('hero_secondary_cta_label_ar', models.CharField(blank=True, max_length=60)),
                ('hero_secondary_cta_destination', models.CharField(blank=True, max_length=255)),
                ('problems_section_title_en', models.CharField(blank=True, max_length=200)),
                ('problems_section_title_ar', models.CharField(blank=True, max_length=200)),
                ('problems_section_desc_en', models.TextField(blank=True)),
                ('problems_section_desc_ar', models.TextField(blank=True)),
                ('solutions_section_title_en', models.CharField(blank=True, max_length=200)),
                ('solutions_section_title_ar', models.CharField(blank=True, max_length=200)),
                ('solutions_section_desc_en', models.TextField(blank=True)),
                ('solutions_section_desc_ar', models.TextField(blank=True)),
                ('process_section_title_en', models.CharField(blank=True, max_length=200)),
                ('process_section_title_ar', models.CharField(blank=True, max_length=200)),
                ('process_section_desc_en', models.TextField(blank=True)),
                ('process_section_desc_ar', models.TextField(blank=True)),
                ('use_cases_section_title_en', models.CharField(blank=True, max_length=200)),
                ('use_cases_section_title_ar', models.CharField(blank=True, max_length=200)),
                ('use_cases_section_desc_en', models.TextField(blank=True)),
                ('use_cases_section_desc_ar', models.TextField(blank=True)),
                ('why_section_title_en', models.CharField(blank=True, max_length=200)),
                ('why_section_title_ar', models.CharField(blank=True, max_length=200)),
                ('why_section_desc_en', models.TextField(blank=True)),
                ('why_section_desc_ar', models.TextField(blank=True)),
                ('faq_section_title_en', models.CharField(blank=True, max_length=200)),
                ('faq_section_title_ar', models.CharField(blank=True, max_length=200)),
                ('cta_title_en', models.CharField(blank=True, max_length=200)),
                ('cta_title_ar', models.CharField(blank=True, max_length=200)),
                ('cta_text_en', models.TextField(blank=True)),
                ('cta_text_ar', models.TextField(blank=True)),
                ('cta_button_label_en', models.CharField(blank=True, max_length=60)),
                ('cta_button_label_ar', models.CharField(blank=True, max_length=60)),
                ('cta_button_destination', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'AI Automation Page',
                'verbose_name_plural': 'AI Automation Page',
                'db_table': 'ai_automation_aiautomationpage',
            },
        ),
        migrations.CreateModel(
            name='AIAutomationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('problems', 'Problems'), ('solutions', 'Solutions'), ('use_cases', 'Use Cases'), ('why', 'Why Us')], help_text='Which section this card belongs to.', max_length=30)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ai_automation.aiautomationpage')),
            ],
            options={
                'verbose_name': 'AI Automation Item',
                'verbose_name_plural': 'AI Automation Items',
                'db_table': 'ai_automation_aiautomationitem',
                'ordering': ['section', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AIAutomationFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_en', models.CharField(blank=True, max_length=500)),
                ('question_ar', models.CharField(blank=True, max_length=500)),
                ('answer_en', models.TextField(blank=True)),
                ('answer_ar', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='ai_automation.aiautomationpage')),
            ],
            options={
                'verbose_name': 'AI Automation FAQ',
                'verbose_name_plural': 'AI Automation FAQs',
                'db_table': 'ai_automation_aiautomationfaq',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AIAutomationProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_number', models.PositiveIntegerField(default=0)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='ai_automation.aiautomationpage')),
            ],
            options={
                'verbose_name': 'AI Automation Process Step',
                'verbose_name_plural': 'AI Automation Process Steps',
                'db_table': 'ai_automation_aiautomationprocessstep',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
