# Generated by Django 6.0.2 on 2026-07-10 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
        ('partners', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_ar', models.CharField(blank=True, max_length=255, verbose_name='Title (Arabic)')),
                ('slug', models.SlugField(help_text='URL-safe identifier.', max_length=255, unique=True, verbose_name='Slug')),
                ('client_name_en', models.CharField(blank=True, max_length=255, verbose_name='Client name (English)')),
                ('client_name_ar', models.CharField(blank=True, max_length=255, verbose_name='Client name (Arabic)')),
                ('short_description_en', models.TextField(blank=True, verbose_name='Short description (English)')),
                ('short_description_ar', models.TextField(blank=True, verbose_name='Short description (Arabic)')),
                ('problem_en', models.TextField(blank=True, verbose_name='Problem (English)')),
                ('problem_ar', models.TextField(blank=True, verbose_name='Problem (Arabic)')),
                ('solution_en', models.TextField(blank=True, verbose_name='Solution (English)')),
                ('solution_ar', models.TextField(blank=True, verbose_name='Solution (Arabic)')),
                ('technology_en', models.TextField(blank=True, verbose_name='Technology (English)')),
                ('technology_ar', models.TextField(blank=True, verbose_name='Technology (Arabic)')),
                ('outcome_en', models.TextField(blank=True, verbose_name='Outcome (English)')),
                ('outcome_ar', models.TextField(blank=True, verbose_name='Outcome (Arabic)')),
                ('industry_en', models.CharField(blank=True, max_length=120, verbose_name='Industry (English)')),
                ('industry_ar', models.CharField(blank=True, max_length=120, verbose_name='Industry (Arabic)')),
                ('project_url', models.URLField(blank=True, verbose_name='Project URL')),
                ('open_in_new_tab', models.BooleanField(default=True, verbose_name='Open in new tab')),
                ('project_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Project year')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower values appear first.', verbose_name='Display order')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive case studies are hidden from public APIs.', verbose_name='Active')),
                ('show_on_homepage', models.BooleanField(default=False, verbose_name='Show on homepage')),
                ('seo_title_en', models.CharField(blank=True, max_length=255, verbose_name='SEO title (English)')),
                ('seo_title_ar', models.CharField(blank=True, max_length=255, verbose_name='SEO title (Arabic)')),
                ('seo_description_en', models.TextField(blank=True, verbose_name='SEO description (English)')),
                ('seo_description_ar', models.TextField(blank=True, verbose_name='SEO description (Arabic)')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediaasset', verbose_name='Featured image')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediaasset', verbose_name='Logo')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_studies', to='partners.partner', verbose_name='Partner')),
                ('services', models.ManyToManyField(blank=True, related_name='case_studies', to='services.service', verbose_name='Services')),
            ],
            options={
                'verbose_name': 'Case Study',
                'verbose_name_plural': 'Case Studies',
                'db_table': 'case_studies_casestudy',
                'ordering': ['display_order', 'title_en'],
                'indexes': [models.Index(fields=['is_active', 'is_featured', 'display_order'], name='cs_active_featured_idx'), models.Index(fields=['is_active', 'show_on_homepage', 'display_order'], name='cs_active_homepage_idx')],
            },
        ),
    ]
