/**
 * CMS Language Context — bilingual interface (Arabic / English).
 *
 * - Persists preference in a cookie (not localStorage).
 * - Controls document direction (RTL / LTR).
 * - Provides t() for interface labels.
 * - Content field direction is independent of interface language.
 */

import { createContext, useCallback, useContext, useEffect, useState } from 'react';

const COOKIE_NAME = 'cms_lang';
const DEFAULT_LANG = 'en';

const translations = {
  en: {
    // Generic
    'app.name': 'Sidrah CMS',
    'action.save': 'Save',
    'action.cancel': 'Cancel',
    'action.delete': 'Delete',
    'action.edit': 'Edit',
    'action.create': 'Create',
    'action.search': 'Search',
    'action.clear': 'Clear',
    'action.previous': 'Previous',
    'action.next': 'Next',
    'action.confirm': 'Confirm',
    'action.close': 'Close',
    'action.back': 'Back to Dashboard',
    'action.retry': 'Retry',
    'action.upload': 'Upload',
    'action.view': 'View',
    'action.moveUp': 'Move Up',
    'action.moveDown': 'Move Down',
    'action.publish': 'Publish',
    'action.unpublish': 'Unpublish',
    'action.archive': 'Archive',
    'action.reorder': 'Save Order',
    'action.addNew': 'Add New',
    'action.refresh': 'Refresh',
    'action.copy': 'Copy',
    'action.copied': 'Copied!',
    'action.previousPage': 'Previous',
    'action.nextPage': 'Next',
    'action.cancelUpload': 'Cancel Upload',
    'action.uploadNew': 'Upload New',
    'action.confirmDelete': 'Confirm Delete',
    'action.editMetadata': 'Edit Metadata',
    'action.change': 'Change',
    'a11y.toggleMenu': 'Toggle navigation menu',
    'a11y.switchLanguage': 'Switch language',
    'a11y.cmsNavigation': 'CMS navigation',
    'a11y.closeDialog': 'Close dialog',
    'a11y.searchPlaceholder': 'Search…',
    'a11y.dismissNotification': 'Dismiss notification',
    'siteSettings.general': 'General',
    'siteSettings.siteName': 'Site Name',
    'siteSettings.siteTagline': 'Site Tagline',
    'siteSettings.defaultLanguage': 'Default Language',
    'siteSettings.supportedLanguages': 'Supported Languages',
    'siteSettings.contact': 'Contact Information',
    'siteSettings.contactEmail': 'Contact Email',
    'siteSettings.recipientEmail': 'Recipient Email',
    'siteSettings.phone': 'Phone',
    'siteSettings.address': 'Address',
    'siteSettings.social': 'Social Media',
    'siteSettings.maps': 'Maps & Location',
    'siteSettings.googleMapsUrl': 'Google Maps URL',
    'siteSettings.mapEmbedUrl': 'Map Embed URL',
    'siteSettings.latitude': 'Latitude',
    'siteSettings.longitude': 'Longitude',
    'siteSettings.workingHours': 'Working Hours',
    'siteSettings.seo': 'Default SEO',
    'siteSettings.metaTitle': 'Default Meta Title',
    'siteSettings.metaDescription': 'Default Meta Description',
    'siteSettings.media': 'Media Assets',
    'siteSettings.ogImage': 'Default OG Image',
    'siteSettings.primaryLogo': 'Primary Logo',
    'siteSettings.secondaryLogo': 'Secondary Logo',
    'siteSettings.favicon': 'Favicon',
    'siteSettings.active': 'Active',
    'siteSettings.permissionDenied': 'You do not have permission to view site settings.',
    'siteSettings.supportedHint': 'Comma-separated, e.g. en,ar',
    'siteSettings.ogHint': 'Recommended: 1200×630px',
    'siteSettings.ogTitle': 'Default OG Title',
    'siteSettings.ogDescription': 'Default OG Description',
    'siteSettings.ogTitleHint': 'Falls back to default meta title if empty',
    'siteSettings.twitterCardType': 'Twitter Card Type',
    'siteSettings.canonicalBaseUrl': 'Canonical Base URL',
    'siteSettings.canonicalBaseUrlHint': 'e.g. https://sidrahsoft.com',
    'siteSettings.robotsIndex': 'Allow search engines to index site',
    'siteSettings.organizationDescription': 'Organization Description',
    'siteSettings.organizationDescriptionHint': 'Used in Organization schema.org structured data',
    'siteSettings.metaTitleHint': 'Recommended length: 50-60 characters',
    'siteSettings.metaDescriptionHint': 'Recommended length: 150-160 characters',
    'media.loadFailed': 'Failed to load media assets.',
    'media.noPreview': 'No preview',
    'media.asset': 'Asset #{id}',
    'media.library': 'Media Library',
    'media.uploadImage': 'Upload Image',
    'media.searchPlaceholder': 'Search by title, alt text, filename…',
    'media.searchAssets': 'Search media assets',
    'media.filterMime': 'Filter by MIME type',
    'media.sortOrder': 'Sort order',
    'media.allTypes': 'All types',
    'media.newest': 'Newest first',
    'media.oldest': 'Oldest first',
    'media.recentlyUpdated': 'Recently updated',
    'media.leastRecentlyUpdated': 'Least recently updated',
    'media.largest': 'Largest size',
    'media.smallest': 'Smallest size',
    'media.titleAZ': 'Title (A-Z)',
    'media.titleZA': 'Title (Z-A)',
    'media.loading': 'Loading media…',
    'media.empty': 'No media assets found.',
    'media.emptyHint': 'Click "Upload Image" to add your first image.',
    'media.assetCount': 'asset',
    'media.assetsCount': 'assets',
    'media.accessDenied': 'Access Denied',
    'media.permissionDenied': 'You do not have permission to access the Media Library.',
    'media.backDashboard': '← Back to Dashboard',
    'media.select': 'Select Media',
    'media.closePicker': 'Close media picker',
    'media.search': 'Search media…',
    'media.chooseImage': 'Choose image to upload',
    'media.uploading': 'Uploading…',
    'media.uploadFailed': 'Upload failed.',
    'media.imageMinWidth': 'Image must be at least {size}px wide (got {actual}px).',
    'media.imageMinHeight': 'Image must be at least {size}px tall (got {actual}px).',
    'media.noAssetsUpload': 'No media assets found. Upload one to get started.',
    'media.pageOf': 'Page {page} of {total}',
    'media.pageNumber': 'Page {page}',
    'media.details': 'Media Details',
    'media.loadDetailsFailed': 'Failed to load media details.',
    'media.closeDetails': 'Close details dialog',
    'media.url': 'Media URL',
    'media.title': 'Title',
    'media.altText': 'Alt text',
    'media.filename': 'Filename',
    'media.mimeType': 'MIME type',
    'media.fileSize': 'File size',
    'media.dimensions': 'Dimensions',
    'media.usageContext': 'Usage context',
    'media.uploadedBy': 'Uploaded by',
    'media.uploadDate': 'Upload date',
    'media.usageCount': 'Usage count',
    'media.usedBy': 'Used by ({count})',
    'media.inUseCannotDelete': 'This asset cannot be deleted because it is currently in use.',
    'media.updateFailed': 'Failed to update metadata.',
    'media.deleteFailed': 'Failed to delete asset.',
    'media.deleteInUse': 'This asset is in use and cannot be deleted. Remove all references first.',
    'media.deleteConfirm': 'Are you sure you want to delete this asset? This cannot be undone.',
    'media.assetInUseTitle': 'Asset is in use — cannot delete',
    'media.deleteTitle': 'Delete this asset',
    'media.upload': 'Upload',
    'media.uploadDialog': 'Upload Image',
    'media.closeUpload': 'Close upload dialog',
    'media.chooseOrDrag': 'Click or drag an image here',
    'media.fileTypesHint': 'JPG, PNG, WebP, GIF — max 5 MB',
    'media.optional': 'optional',
    'media.usageHint': 'e.g. partner logo, insight cover',
    'media.fileSizeLimit': 'File size exceeds 5 MB limit (got {size} MB).',
    'media.extensionNotAllowed': 'Extension ".{ext}" is not allowed. Allowed: .jpg, .jpeg, .png, .webp, .gif',
    'media.cancel': 'Cancel',

    // States
    'state.loading': 'Loading…',
    'state.error': 'An error occurred.',
    'state.empty': 'No records found.',
    'state.forbidden': 'Access Denied',
    'state.notFound': 'Page Not Found',
    'state.saving': 'Saving…',
    'state.deleting': 'Deleting…',
    'state.noData': 'No data available.',

    // Messages
    'msg.saved': 'Changes saved successfully.',
    'msg.created': 'Record created successfully.',
    'msg.deleted': 'Record deleted successfully.',
    'msg.deleteFailed': 'Failed to delete record.',
    'msg.saveFailed': 'Failed to save changes.',
    'msg.loadFailed': 'Failed to load data.',
    'msg.networkError': 'Network error. Please check your connection.',
    'msg.sessionExpired': 'Session expired. Please log in again.',
    'msg.conflict': 'This item is referenced and cannot be deleted.',
    'msg.orderSaved': 'Order saved successfully.',
    'msg.published': 'Article published successfully.',
    'msg.unpublished': 'Article unpublished successfully.',
    'msg.archived': 'Article archived successfully.',
    'msg.unsavedChanges': 'You have unsaved changes. Are you sure you want to leave?',
    'msg.unsavedIndicator': 'Unsaved changes',

    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.siteSettings': 'Site Settings',
    'nav.navigation': 'Navigation',
    'nav.partners': 'Partners',
    'nav.services': 'Services',
    'nav.caseStudies': 'Case Studies',
    'nav.insights': 'Insights',
    'nav.careers': 'Careers',
    'nav.contact': 'Contact',
    'nav.media': 'Media Library',
    'nav.activityLogs': 'Activity Logs',
    'nav.users': 'Users',
    'nav.inquiryTypes': 'Inquiry Types',
    'nav.submissions': 'Submissions',
    'nav.homepage': 'Homepage',

    // Homepage management
    'homepage.title': 'Homepage Management',
    'homepage.subtitle': 'Manage homepage sections, hero, foundation, marquee, and industries',
    'homepage.tab.hero': 'Hero',
    'homepage.tab.foundation': 'Foundation',
    'homepage.tab.marquee': 'Marquee',
    'homepage.tab.industries': 'Industries',
    'homepage.tab.layout': 'Layout',
    'homepage.heroEnabled': 'Hero Section Enabled',
    'homepage.heroScopeNote': 'The cinematic hero is an animation-based section with no text overlays. Only visibility and location card controls are supported.',
    'homepage.heroHeadlineEn': 'Hero Headline (EN)',
    'homepage.heroHeadlineAr': 'Hero Headline (AR)',
    'homepage.heroSubheadlineEn': 'Hero Subheadline (EN)',
    'homepage.heroSubheadlineAr': 'Hero Subheadline (AR)',
    'homepage.heroPrimaryCtaLabelEn': 'Primary CTA Label (EN)',
    'homepage.heroPrimaryCtaLabelAr': 'Primary CTA Label (AR)',
    'homepage.heroPrimaryCtaTarget': 'Primary CTA Target',
    'homepage.heroSecondaryCtaLabelEn': 'Secondary CTA Label (EN)',
    'homepage.heroSecondaryCtaLabelAr': 'Secondary CTA Label (AR)',
    'homepage.heroSecondaryCtaTarget': 'Secondary CTA Target',
    'homepage.heroMedia': 'Hero Media',
    'homepage.heroShowLocationCard': 'Show Location Card',
    'homepage.foundationEnabled': 'Foundation Enabled',
    'homepage.foundationEyebrowEn': 'Eyebrow (EN)',
    'homepage.foundationEyebrowAr': 'Eyebrow (AR)',
    'homepage.foundationHeadingEn': 'Heading (EN)',
    'homepage.foundationHeadingAr': 'Heading (AR)',
    'homepage.foundationDescriptionEn': 'Description (EN)',
    'homepage.foundationDescriptionAr': 'Description (AR)',
    'homepage.foundationProofPointsEn': 'Proof Points (EN)',
    'homepage.foundationProofPointsAr': 'Proof Points (AR)',
    'homepage.foundationProofPointsHint': 'One per line',
    'homepage.foundationCtaLabelEn': 'CTA Label (EN)',
    'homepage.foundationCtaLabelAr': 'CTA Label (AR)',
    'homepage.foundationCtaTarget': 'CTA Target',
    'homepage.marqueeHeadingEn': 'Heading (EN)',
    'homepage.marqueeHeadingAr': 'Heading (AR)',
    'homepage.marqueeAddItem': 'Add Marquee Item',
    'homepage.marqueeEditItem': 'Edit Marquee Item',
    'homepage.marqueeTitleEn': 'Title (EN)',
    'homepage.marqueeTitleAr': 'Title (AR)',
    'homepage.marqueeDescriptionEn': 'Description (EN)',
    'homepage.marqueeDescriptionAr': 'Description (AR)',
    'homepage.marqueeConfirmDelete': 'Are you sure you want to delete this marquee item?',
    'homepage.industriesHeadingEn': 'Section Heading (EN)',
    'homepage.industriesHeadingAr': 'Section Heading (AR)',
    'homepage.industriesDescriptionEn': 'Section Description (EN)',
    'homepage.industriesDescriptionAr': 'Section Description (AR)',
    'homepage.industriesAdd': 'Add Industry',
    'homepage.industriesEdit': 'Edit Industry',
    'homepage.industriesTitleEn': 'Title (EN)',
    'homepage.industriesTitleAr': 'Title (AR)',
    'homepage.industriesDescriptionEn2': 'Description (EN)',
    'homepage.industriesDescriptionAr2': 'Description (AR)',
    'homepage.industriesFocusAreasEn': 'Focus Areas (EN)',
    'homepage.industriesFocusAreasAr': 'Focus Areas (AR)',
    'homepage.industriesFocusAreasHint': 'One per line',
    'homepage.industriesIcon': 'Icon',
    'homepage.industriesConfirmDelete': 'Are you sure you want to delete this industry?',
    'homepage.layoutSection': 'Section',
    'homepage.layoutOrder': 'Order',
    'homepage.layoutVisible': 'Visible',
    'homepage.layoutHint': 'Toggle visibility and set display order for homepage sections',
    'homepage.partnersHeadingEn': 'Partners Heading (EN)',
    'homepage.partnersHeadingAr': 'Partners Heading (AR)',
    'homepage.partnersDescriptionEn': 'Partners Description (EN)',
    'homepage.partnersDescriptionAr': 'Partners Description (AR)',
    'homepage.caseStudiesHeadingEn': 'Case Studies Heading (EN)',
    'homepage.caseStudiesHeadingAr': 'Case Studies Heading (AR)',
    'homepage.caseStudiesDescriptionEn': 'Case Studies Description (EN)',
    'homepage.caseStudiesDescriptionAr': 'Case Studies Description (AR)',
    'homepage.insightsHeadingEn': 'Insights Heading (EN)',
    'homepage.insightsHeadingAr': 'Insights Heading (AR)',
    'homepage.insightsDescriptionEn': 'Insights Description (EN)',
    'homepage.insightsDescriptionAr': 'Insights Description (AR)',
    'homepage.careersHeadingEn': 'Careers Heading (EN)',
    'homepage.careersHeadingAr': 'Careers Heading (AR)',
    'homepage.careersDescriptionEn': 'Careers Description (EN)',
    'homepage.careersDescriptionAr': 'Careers Description (AR)',
    'homepage.settingsSaved': 'Homepage settings saved successfully.',
    'homepage.saveFailed': 'Failed to save homepage settings.',
    'homepage.noItems': 'No items found.',
    'homepage.loadFailed': 'Failed to load homepage data.',
    'homepage.tab.sectionHeadings': 'Section Headings',
    'homepage.itemCreated': 'Item created successfully.',
    'homepage.itemUpdated': 'Item updated successfully.',
    'homepage.itemDeleted': 'Item deleted successfully.',
    'homepage.sectionUpdated': 'Section updated successfully.',
    'homepage.sectionDeleted': 'Section deleted successfully.',
    'homepage.invalidSectionKey': 'Invalid section key.',
    'homepage.duplicateSectionKey': 'This section key already exists.',

    // User management
    'users.title': 'User Management',
    'users.subtitle': 'Manage CMS users, roles, and access',
    'users.createUser': 'Create User',
    'users.editUser': 'Edit User',
    'users.resetPassword': 'Reset Password',
    'users.activate': 'Activate',
    'users.deactivate': 'Deactivate',
    'users.confirmDeactivate': 'Are you sure you want to deactivate this user? They will lose CMS access immediately.',
    'users.confirmActivate': 'Are you sure you want to activate this user?',
    'users.confirmReset': 'Are you sure you want to reset this user\'s password?',
    'users.noUsers': 'No users found.',
    'users.loadFailed': 'Failed to load users.',
    'users.name': 'Name',
    'users.actions': 'Actions',
    'users.you': '(You)',
    'users.allRoles': 'All roles',
    'users.allStatuses': 'All statuses',
    'users.active': 'Active',
    'users.inactive': 'Inactive',
    'users.created': 'User created successfully.',
    'users.updated': 'User updated successfully.',
    'users.activated': 'User activated successfully.',
    'users.deactivated': 'User deactivated successfully.',
    'users.passwordReset': 'Password reset successfully.',
    'users.createFailed': 'Failed to create user.',
    'users.updateFailed': 'Failed to update user.',
    'users.activateFailed': 'Failed to activate user.',
    'users.deactivateFailed': 'Failed to deactivate user.',
    'users.resetFailed': 'Failed to reset password.',
    'users.roleSuperAdmin': 'Super Admin',
    'users.roleAdmin': 'Admin',
    'users.roleContentManager': 'Content Manager',
    'users.roleEditor': 'Editor',
    'users.roleMarketingManager': 'Marketing Manager',
    'users.roleMarketingSeo': 'Marketing / SEO',
    'users.roleRecruiter': 'Recruiter',
    'users.roleSupportAgent': 'Support Agent',
    'users.roleSupportRecruiter': 'Support / Recruiter',
    'users.roleLmsAdmin': 'LMS Admin',
    'users.roleFinanceSales': 'Finance / Sales',
    'form.username': 'Username',
    'form.password': 'Password',
    'form.passwordConfirm': 'Confirm Password',
    'form.role': 'Role',
    'form.status': 'Status',
    'form.dateJoined': 'Date Joined',
    'form.lastLogin': 'Last Login',

    // Dashboard
    'dash.welcome': 'Welcome',
    'dash.quickActions': 'Quick Actions',
    'dash.recentActivity': 'Recent Activity',
    'dash.recentSubmissions': 'Recent Contact Submissions',
    'dash.stats': 'Statistics',
    'dash.total': 'Total',
    'dash.active': 'Active',
    'dash.featured': 'Featured',
    'dash.draft': 'Draft',
    'dash.published': 'Published',
    'dash.archived': 'Archived',
    'dash.expired': 'Expired',
    'dash.new': 'New',
    'dash.onHomepage': 'On Homepage',
    'dash.media': 'Media Assets',
    'dash.images': 'Images',
    'dash.documents': 'Documents',
    'dash.users': 'Users',
    'dash.inactive': 'Inactive',
    'dash.byRole': 'By Role',
    'dash.highPriority': 'High Priority',
    'dash.recentCount': 'Recent (7d)',
    'dash.inquiryType': 'Inquiry Type',
    'dash.priority': 'Priority',
    'dash.noActivity': 'No recent activity',
    'dash.noSubmissions': 'No recent submissions',
    'dash.createInsight': 'Create Insight',
    'dash.addService': 'Add Service',
    'dash.addPartner': 'Add Partner',
    'dash.addCaseStudy': 'Add Case Study',
    'dash.addJob': 'Add Job',
    'dash.openContact': 'Contact Submissions',
    'dash.uploadMedia': 'Upload Media',
    'dash.manageUsers': 'Manage Users',

    // Forms
    'form.english': 'English',
    'form.arabic': 'Arabic',
    'form.title': 'Title',
    'form.name': 'Name',
    'form.slug': 'Slug',
    'form.description': 'Description',
    'form.status': 'Status',
    'form.priority': 'Priority',
    'form.type': 'Type',
    'form.order': 'Display Order',
    'form.featured': 'Featured',
    'form.active': 'Active',
    'form.visible': 'Visible',
    'form.homepage': 'Show on Homepage',
    'form.seo': 'SEO Settings',
    'form.image': 'Image',
    'form.icon': 'Icon',
    'form.logo': 'Logo',
    'form.selectImage': 'Select Image',
    'form.removeImage': 'Remove',
    'form.noImage': 'No image selected',
    'form.created': 'Created',
    'form.updated': 'Updated',
    'form.publishedAt': 'Published At',
    'form.author': 'Author',
    'form.category': 'Category',
    'form.excerpt': 'Excerpt',
    'form.body': 'Body Content',
    'form.contentType': 'Content Type',
    'form.readTime': 'Read Time (minutes)',
    'form.clientName': 'Client Name',
    'form.industry': 'Industry',
    'form.shortDescription': 'Short Description',
    'form.problem': 'Problem',
    'form.solution': 'Solution',
    'form.technology': 'Technology',
    'form.outcome': 'Outcome',
    'form.featuredImage': 'Featured Image',
    'form.partnerId': 'Partner ID',
    'form.projectUrl': 'Project URL',
    'form.projectYear': 'Project Year',
    'form.department': 'Department',
    'form.location': 'Location',
    'form.responsibilities': 'Responsibilities',
    'form.requirements': 'Requirements',
    'form.preferredQualifications': 'Preferred Qualifications',
    'form.benefits': 'Benefits',
    'form.employmentType': 'Employment Type',
    'form.workplaceType': 'Workplace Type',
    'form.experienceLevel': 'Experience Level',
    'form.applicationMethod': 'Application Method',
    'form.applicationEmail': 'Application Email',
    'form.externalApplyUrl': 'External Apply URL',
    'form.postedDate': 'Posted Date',
    'form.closingDate': 'Closing Date',
    'form.assignedTo': 'Assigned To',
    'form.internalNotes': 'Internal Notes',
    'form.ctaUrl': 'CTA URL',
    'form.ctaLabel': 'CTA Label',
    'form.seoTitle': 'SEO Title',
    'form.seoDescription': 'SEO Description',
    'form.seoTitleHint': 'Recommended length: 50-60 characters',
    'form.seoDescriptionHint': 'Recommended length: 150-160 characters',
    'form.canonicalUrl': 'Canonical URL Override',
    'form.canonicalUrlHint': 'Leave blank to use the default URL',
    'form.openGraph': 'Open Graph',
    'form.ogTitle': 'OG Title',
    'form.ogTitleHint': 'Falls back to SEO title if empty',
    'form.ogDescription': 'OG Description',
    'form.ogImage': 'OG Image',
    'form.ogImageHint': 'Falls back to featured image if empty',
    'form.robotsDirectives': 'Robots Directives',
    'form.robotsIndex': 'Allow search engines to index',
    'form.robotsFollow': 'Allow search engines to follow links',
    'form.openInNewTab': 'Open in New Tab',
    'form.partnerType': 'Partner Type',
    'form.websiteUrl': 'Website URL',
    'form.linkType': 'Link Type',
    'form.routeName': 'Route Name',
    'form.url': 'URL',
    'form.anchor': 'Anchor',
    'form.iconCssClass': 'Icon (CSS class)',
    'form.iconAsset': 'Icon Asset',
    'form.label': 'Label',
    'form.target': 'Target',
    'nav.menu': 'Menu',
    'nav.item': 'Item',
    'form.email': 'Email',
    'form.firstName': 'First Name',
    'form.lastName': 'Last Name',
    'form.phone': 'Phone',
    'form.company': 'Company',
    'form.date': 'Date',
    'form.message': 'Message',
    'contact.inquiryType': 'Inquiry Type',

    // Status labels
    'status.new': 'New',
    'status.contacted': 'Contacted',
    'status.inProgress': 'In Progress',
    'status.closed': 'Closed',
    'status.spam': 'Spam',
    'status.archived': 'Archived',

    // Priority labels
    'priority.low': 'Low',
    'priority.medium': 'Medium',
    'priority.high': 'High',
    'priority.urgent': 'Urgent',

    // Leads dashboard
    'leads.title': 'Leads',
    'leads.signIn': 'Sign In',
    'leads.loginSubtitle': 'Access your lead management workspace.',
    'leads.loading': 'Loading…',
    'leads.signingIn': 'Signing in…',
    'leads.networkError': 'Unable to connect to the server. Please check your connection and try again.',
    'leads.loginFailed': 'Login failed.',
    'leads.dashboard': 'Lead Dashboard',
    'leads.subtitle': 'Manage, prioritise and respond to incoming leads.',
    'leads.total': 'Total Leads',
    'leads.new': 'New',
    'leads.contacted': 'Contacted',
    'leads.itemCount': 'lead',
    'leads.itemsCount': 'leads',
    'leads.noLeadsFiltered': 'No leads match your filters. Clear them to start over.',
    'leads.closed': 'Closed',
    'leads.allStatuses': 'All statuses',
    'leads.allPriorities': 'All priorities',
    'leads.allTypes': 'All types',
    'leads.openDetail': 'Open',
    'leads.copyEmail': 'Copy email',
    'leads.emailCopied': 'Copied!',
    'leads.openEmailClient': 'Open in email client',
    'leads.noLeads': 'No leads found.',
    'leads.loadFailed': 'Failed to load leads.',
    'leads.notFound': 'Lead not found.',
    'leads.backToLeads': 'Back to leads',
    'leads.contactInfo': 'Contact Information',
    'leads.message': 'Message',
    'leads.source': 'Source',
    'leads.language': 'Language',
    'leads.inquiryType': 'Inquiry Type',
    'leads.markSpam': 'Mark as spam',
    'leads.markedSpam': 'Marked as spam.',
    'leads.archive': 'Archive',
    'leads.archived': 'Archived.',
    'leads.confirmSpam': 'Are you sure you want to mark "{name}" as spam? This can be undone by changing the status.',
    'leads.confirmArchive': 'Are you sure you want to archive "{name}"? Archived leads are hidden from the default view.',
    'leads.copyFailed': 'Failed to copy email.',
    'leads.jobTitle': 'Job Title',
    'leads.subject': 'Subject',
    'leads.manageLead': 'Manage Lead',
    'leads.save': 'Save changes',
    'leads.saveSuccess': 'Changes saved.',
    'leads.saveFailed': 'Failed to save changes.',
    'leads.status': 'Status',
    'leads.priority': 'Priority',
    'leads.internalNotes': 'Internal Notes',
    'leads.notesHint': 'Private notes visible only to your team.',

    // Confirm
    'confirm.delete.title': 'Confirm Delete',
    'confirm.delete.message': 'Are you sure you want to delete "{name}"? This action cannot be undone.',
    'confirm.publish.title': 'Confirm Publish',
    'confirm.publish.message': 'Are you sure you want to publish "{name}"?',
    'confirm.archive.title': 'Confirm Archive',
    'confirm.archive.message': 'Are you sure you want to archive "{name}"?',

    // User
    'user.role': 'Role',
    'user.signOut': 'Sign Out',
    'user.language': 'Language',

    // Common
    'common.loading': 'Loading...',
    'common.accessDenied': 'Access Denied',
    'common.accessDeniedText': 'Your account does not have access to this module.',
    'common.contactAdmin': 'Contact a system administrator if you believe this is an error.',
    'common.retry': 'Retry',
  },
  ar: {
    // Generic
    'app.name': 'سدرة CMS',
    'action.save': 'حفظ',
    'action.cancel': 'إلغاء',
    'action.delete': 'حذف',
    'action.edit': 'تعديل',
    'action.create': 'إنشاء',
    'action.search': 'بحث',
    'action.clear': 'مسح',
    'action.previous': 'السابق',
    'action.next': 'التالي',
    'action.confirm': 'تأكيد',
    'action.close': 'إغلاق',
    'action.back': 'العودة للوحة التحكم',
    'action.retry': 'إعادة المحاولة',
    'action.upload': 'رفع',
    'action.view': 'عرض',
    'action.moveUp': 'تحريك لأعلى',
    'action.moveDown': 'تحريك لأسفل',
    'action.publish': 'نشر',
    'action.unpublish': 'إلغاء النشر',
    'action.archive': 'أرشفة',
    'action.reorder': 'حفظ الترتيب',
    'action.addNew': 'إضافة جديد',
    'action.refresh': 'تحديث',
    'action.copy': 'نسخ',
    'action.copied': 'تم النسخ!',
    'action.previousPage': 'السابق',
    'action.nextPage': 'التالي',
    'action.cancelUpload': 'إلغاء الرفع',
    'action.uploadNew': 'رفع جديد',
    'action.confirmDelete': 'تأكيد الحذف',
    'action.editMetadata': 'تعديل البيانات الوصفية',
    'action.change': 'تغيير',
    'a11y.toggleMenu': 'تبديل قائمة التنقل',
    'a11y.switchLanguage': 'تبديل اللغة',
    'a11y.cmsNavigation': 'تنقل لوحة التحكم',
    'a11y.closeDialog': 'إغلاق النافذة',
    'a11y.searchPlaceholder': 'بحث…',
    'a11y.dismissNotification': 'إغلاق الإشعار',
    'siteSettings.general': 'عام',
    'siteSettings.siteName': 'اسم الموقع',
    'siteSettings.siteTagline': 'شعار الموقع',
    'siteSettings.defaultLanguage': 'اللغة الافتراضية',
    'siteSettings.supportedLanguages': 'اللغات المدعومة',
    'siteSettings.contact': 'معلومات الاتصال',
    'siteSettings.contactEmail': 'البريد الإلكتروني للاتصال',
    'siteSettings.recipientEmail': 'البريد الإلكتروني للمستلم',
    'siteSettings.phone': 'الهاتف',
    'siteSettings.address': 'العنوان',
    'siteSettings.social': 'التواصل الاجتماعي',
    'siteSettings.maps': 'الخرائط والموقع',
    'siteSettings.googleMapsUrl': 'رابط خرائط Google',
    'siteSettings.mapEmbedUrl': 'رابط تضمين الخريطة',
    'siteSettings.latitude': 'خط العرض',
    'siteSettings.longitude': 'خط الطول',
    'siteSettings.workingHours': 'ساعات العمل',
    'siteSettings.seo': 'تحسين محركات البحث الافتراضي',
    'siteSettings.metaTitle': 'عنوان Meta الافتراضي',
    'siteSettings.metaDescription': 'وصف Meta الافتراضي',
    'siteSettings.media': 'أصول الوسائط',
    'siteSettings.ogImage': 'صورة OG الافتراضية',
    'siteSettings.primaryLogo': 'الشعار الأساسي',
    'siteSettings.secondaryLogo': 'الشعار الثانوي',
    'siteSettings.favicon': 'الأيقونة المفضلة',
    'siteSettings.active': 'نشط',
    'siteSettings.permissionDenied': 'ليس لديك صلاحية لعرض إعدادات الموقع.',
    'siteSettings.supportedHint': 'مفصولة بفواصل، مثال: en,ar',
    'siteSettings.ogHint': 'موصى به: 1200×630px',
    'siteSettings.ogTitle': 'عنوان OG الافتراضي',
    'siteSettings.ogDescription': 'وصف OG الافتراضي',
    'siteSettings.ogTitleHint': 'يستخدم عنوان Meta الافتراضي إذا كان فارغاً',
    'siteSettings.twitterCardType': 'نوع بطاقة تويتر',
    'siteSettings.canonicalBaseUrl': 'الرابط الأساسي',
    'siteSettings.canonicalBaseUrlHint': 'مثال: https://sidrahsoft.com',
    'siteSettings.robotsIndex': 'السماح لمحركات البحث بفهرسة الموقع',
    'siteSettings.organizationDescription': 'وصف المؤسسة',
    'siteSettings.organizationDescriptionHint': 'يستخدم في بيانات schema.org المنظمة',
    'siteSettings.metaTitleHint': 'الطول الموصى به: 50-60 حرف',
    'siteSettings.metaDescriptionHint': 'الطول الموصى به: 150-160 حرف',
    'media.loadFailed': 'فشل تحميل أصول الوسائط.',
    'media.noPreview': 'لا توجد معاينة',
    'media.asset': 'أصل #{id}',
    'media.library': 'مكتبة الوسائط',
    'media.uploadImage': 'رفع صورة',
    'media.searchPlaceholder': 'البحث بالعنوان أو النص البديل أو اسم الملف…',
    'media.searchAssets': 'البحث في أصول الوسائط',
    'media.filterMime': 'تصفية حسب نوع MIME',
    'media.sortOrder': 'ترتيب الفرز',
    'media.allTypes': 'كل الأنواع',
    'media.newest': 'الأحدث أولاً',
    'media.oldest': 'الأقدم أولاً',
    'media.recentlyUpdated': 'المحدثة مؤخراً',
    'media.leastRecentlyUpdated': 'الأقل تحديثاً مؤخراً',
    'media.largest': 'الأكبر حجماً',
    'media.smallest': 'الأصغر حجماً',
    'media.titleAZ': 'العنوان (أ-ي)',
    'media.titleZA': 'العنوان (ي-أ)',
    'media.loading': 'جاري تحميل الوسائط…',
    'media.empty': 'لم يتم العثور على أصول وسائط.',
    'media.emptyHint': 'اضغط على "رفع صورة" لإضافة أول صورة.',
    'media.assetCount': 'أصل',
    'media.assetsCount': 'أصول',
    'media.accessDenied': 'الوصول مرفوض',
    'media.permissionDenied': 'ليس لديك صلاحية للوصول إلى مكتبة الوسائط.',
    'media.backDashboard': '← العودة إلى لوحة التحكم',
    'media.select': 'اختيار وسائط',
    'media.closePicker': 'إغلاق منتقي الوسائط',
    'media.search': 'البحث في الوسائط…',
    'media.chooseImage': 'اختيار صورة للرفع',
    'media.uploading': 'جاري الرفع…',
    'media.uploadFailed': 'فشل الرفع.',
    'media.imageMinWidth': 'يجب ألا يقل عرض الصورة عن {size}px (الحالي {actual}px).',
    'media.imageMinHeight': 'يجب ألا يقل ارتفاع الصورة عن {size}px (الحالي {actual}px).',
    'media.noAssetsUpload': 'لم يتم العثور على أصول وسائط. ارفع واحداً للبدء.',
    'media.pageOf': 'صفحة {page} من {total}',
    'media.pageNumber': 'صفحة {page}',
    'media.details': 'تفاصيل الوسائط',
    'media.loadDetailsFailed': 'فشل تحميل تفاصيل الوسائط.',
    'media.closeDetails': 'إغلاق نافذة التفاصيل',
    'media.url': 'رابط الوسائط',
    'media.title': 'العنوان',
    'media.altText': 'النص البديل',
    'media.filename': 'اسم الملف',
    'media.mimeType': 'نوع MIME',
    'media.fileSize': 'حجم الملف',
    'media.dimensions': 'الأبعاد',
    'media.usageContext': 'سياق الاستخدام',
    'media.uploadedBy': 'تم الرفع بواسطة',
    'media.uploadDate': 'تاريخ الرفع',
    'media.usageCount': 'عدد الاستخدامات',
    'media.usedBy': 'مستخدم بواسطة ({count})',
    'media.inUseCannotDelete': 'لا يمكن حذف هذا الأصل لأنه مستخدم حالياً.',
    'media.updateFailed': 'فشل تحديث البيانات الوصفية.',
    'media.deleteFailed': 'فشل حذف الأصل.',
    'media.deleteInUse': 'هذا الأصل مستخدم ولا يمكن حذفه. أزل جميع المراجع أولاً.',
    'media.deleteConfirm': 'هل أنت متأكد من حذف هذا الأصل؟ لا يمكن التراجع عن ذلك.',
    'media.assetInUseTitle': 'الأصل مستخدم — لا يمكن حذفه',
    'media.deleteTitle': 'حذف هذا الأصل',
    'media.upload': 'رفع',
    'media.uploadDialog': 'رفع صورة',
    'media.closeUpload': 'إغلاق نافذة الرفع',
    'media.chooseOrDrag': 'اضغط أو اسحب صورة هنا',
    'media.fileTypesHint': 'JPG، PNG، WebP، GIF — الحد الأقصى 5 MB',
    'media.optional': 'اختياري',
    'media.usageHint': 'مثال: شعار شريك، غلاف رؤية',
    'media.fileSizeLimit': 'يتجاوز حجم الملف حد 5 MB (الحجم {size} MB).',
    'media.extensionNotAllowed': 'الامتداد ".{ext}" غير مسموح. المسموح: .jpg، .jpeg، .png، .webp، .gif',
    'media.cancel': 'إلغاء',

    // States
    'state.loading': 'جاري التحميل…',
    'state.error': 'حدث خطأ.',
    'state.empty': 'لا توجد سجلات.',
    'state.forbidden': 'تم رفض الوصول',
    'state.notFound': 'الصفحة غير موجودة',
    'state.saving': 'جاري الحفظ…',
    'state.deleting': 'جاري الحذف…',
    'state.noData': 'لا توجد بيانات.',

    // Messages
    'msg.saved': 'تم حفظ التغييرات بنجاح.',
    'msg.created': 'تم إنشاء السجل بنجاح.',
    'msg.deleted': 'تم حذف السجل بنجاح.',
    'msg.deleteFailed': 'فشل حذف السجل.',
    'msg.saveFailed': 'فشل حفظ التغييرات.',
    'msg.loadFailed': 'فشل تحميل البيانات.',
    'msg.networkError': 'خطأ في الشبكة. يرجى التحقق من اتصالك.',
    'msg.sessionExpired': 'انتهت الجلسة. يرجى تسجيل الدخول مرة أخرى.',
    'msg.conflict': 'هذا العنصر مرتبط بسجلات أخرى ولا يمكن حذفه.',
    'msg.orderSaved': 'تم حفظ الترتيب بنجاح.',
    'msg.published': 'تم نشر المقال بنجاح.',
    'msg.unpublished': 'تم إلغاء نشر المقال بنجاح.',
    'msg.archived': 'تمت أرشفة المقال بنجاح.',
    'msg.unsavedChanges': 'لديك تغييرات غير محفوظة. هل أنت متأكد أنك تريد المغادرة؟',
    'msg.unsavedIndicator': 'تغييرات غير محفوظة',

    // Navigation
    'nav.dashboard': 'لوحة التحكم',
    'nav.siteSettings': 'إعدادات الموقع',
    'nav.navigation': 'التنقل',
    'nav.partners': 'الشركاء',
    'nav.services': 'الخدمات',
    'nav.caseStudies': 'دراسات الحالة',
    'nav.insights': 'الرؤى',
    'nav.careers': 'الوظائف',
    'nav.contact': 'التواصل',
    'nav.media': 'مكتبة الوسائط',
    'nav.activityLogs': 'سجل النشاط',
    'nav.users': 'المستخدمون',
    'nav.inquiryTypes': 'أنواع الاستفسارات',
    'nav.submissions': 'الطلبات',
    'nav.homepage': 'الصفحة الرئيسية',

    // Homepage management
    'homepage.title': 'إدارة الصفحة الرئيسية',
    'homepage.subtitle': 'إدارة أقسام الصفحة الرئيسية والهيرو والأساس والشريط المتحرك والصناعات',
    'homepage.tab.hero': 'الهيرو',
    'homepage.tab.foundation': 'الأساس',
    'homepage.tab.marquee': 'الشريط المتحرك',
    'homepage.tab.industries': 'الصناعات',
    'homepage.tab.layout': 'التخطيط',
    'homepage.heroEnabled': 'تفعيل قسم الهيرو',
    'homepage.heroScopeNote': 'الهيرو السينمائي هو قسم قائم على الرسوم المتحركة بدون نصوص. فقط التحكم في الظهور وبطاقة الموقع مدعوم.',
    'homepage.heroHeadlineEn': 'عنوان الهيرو (EN)',
    'homepage.heroHeadlineAr': 'عنوان الهيرو (AR)',
    'homepage.heroSubheadlineEn': 'العنوان الفرعي للهيرو (EN)',
    'homepage.heroSubheadlineAr': 'العنوان الفرعي للهيرو (AR)',
    'homepage.heroPrimaryCtaLabelEn': 'زر CTA الرئيسي (EN)',
    'homepage.heroPrimaryCtaLabelAr': 'زر CTA الرئيسي (AR)',
    'homepage.heroPrimaryCtaTarget': 'هدف CTA الرئيسي',
    'homepage.heroSecondaryCtaLabelEn': 'زر CTA الثانوي (EN)',
    'homepage.heroSecondaryCtaLabelAr': 'زر CTA الثانوي (AR)',
    'homepage.heroSecondaryCtaTarget': 'هدف CTA الثانوي',
    'homepage.heroMedia': 'وسائط الهيرو',
    'homepage.heroShowLocationCard': 'إظهار بطاقة الموقع',
    'homepage.foundationEnabled': 'تفعيل القسم التأسيسي',
    'homepage.foundationEyebrowEn': 'العنوان الصغير (EN)',
    'homepage.foundationEyebrowAr': 'العنوان الصغير (AR)',
    'homepage.foundationHeadingEn': 'العنوان (EN)',
    'homepage.foundationHeadingAr': 'العنوان (AR)',
    'homepage.foundationDescriptionEn': 'الوصف (EN)',
    'homepage.foundationDescriptionAr': 'الوصف (AR)',
    'homepage.foundationProofPointsEn': 'نقاط الإثبات (EN)',
    'homepage.foundationProofPointsAr': 'نقاط الإثبات (AR)',
    'homepage.foundationProofPointsHint': 'واحد في كل سطر',
    'homepage.foundationCtaLabelEn': 'زر CTA (EN)',
    'homepage.foundationCtaLabelAr': 'زر CTA (AR)',
    'homepage.foundationCtaTarget': 'هدف CTA',
    'homepage.marqueeHeadingEn': 'العنوان (EN)',
    'homepage.marqueeHeadingAr': 'العنوان (AR)',
    'homepage.marqueeAddItem': 'إضافة عنصر',
    'homepage.marqueeEditItem': 'تعديل عنصر',
    'homepage.marqueeTitleEn': 'العنوان (EN)',
    'homepage.marqueeTitleAr': 'العنوان (AR)',
    'homepage.marqueeDescriptionEn': 'الوصف (EN)',
    'homepage.marqueeDescriptionAr': 'الوصف (AR)',
    'homepage.marqueeConfirmDelete': 'هل أنت متأكد أنك تريد حذف هذا العنصر؟',
    'homepage.industriesHeadingEn': 'عنوان القسم (EN)',
    'homepage.industriesHeadingAr': 'عنوان القسم (AR)',
    'homepage.industriesDescriptionEn': 'وصف القسم (EN)',
    'homepage.industriesDescriptionAr': 'وصف القسم (AR)',
    'homepage.industriesAdd': 'إضافة صناعة',
    'homepage.industriesEdit': 'تعديل صناعة',
    'homepage.industriesTitleEn': 'العنوان (EN)',
    'homepage.industriesTitleAr': 'العنوان (AR)',
    'homepage.industriesDescriptionEn2': 'الوصف (EN)',
    'homepage.industriesDescriptionAr2': 'الوصف (AR)',
    'homepage.industriesFocusAreasEn': 'مجالات التركيز (EN)',
    'homepage.industriesFocusAreasAr': 'مجالات التركيز (AR)',
    'homepage.industriesFocusAreasHint': 'واحد في كل سطر',
    'homepage.industriesIcon': 'الأيقونة',
    'homepage.industriesConfirmDelete': 'هل أنت متأكد أنك تريد حذف هذه الصناعة؟',
    'homepage.layoutSection': 'القسم',
    'homepage.layoutOrder': 'الترتيب',
    'homepage.layoutVisible': 'مرئي',
    'homepage.layoutHint': 'تحكم في الرؤية وترتيب عرض أقسام الصفحة الرئيسية',
    'homepage.partnersHeadingEn': 'عنوان الشركاء (EN)',
    'homepage.partnersHeadingAr': 'عنوان الشركاء (AR)',
    'homepage.partnersDescriptionEn': 'وصف الشركاء (EN)',
    'homepage.partnersDescriptionAr': 'وصف الشركاء (AR)',
    'homepage.caseStudiesHeadingEn': 'عنوان دراسات الحالة (EN)',
    'homepage.caseStudiesHeadingAr': 'عنوان دراسات الحالة (AR)',
    'homepage.caseStudiesDescriptionEn': 'وصف دراسات الحالة (EN)',
    'homepage.caseStudiesDescriptionAr': 'وصف دراسات الحالة (AR)',
    'homepage.insightsHeadingEn': 'عنوان الرؤى (EN)',
    'homepage.insightsHeadingAr': 'عنوان الرؤى (AR)',
    'homepage.insightsDescriptionEn': 'وصف الرؤى (EN)',
    'homepage.insightsDescriptionAr': 'وصف الرؤى (AR)',
    'homepage.careersHeadingEn': 'عنوان الوظائف (EN)',
    'homepage.careersHeadingAr': 'عنوان الوظائف (AR)',
    'homepage.careersDescriptionEn': 'وصف الوظائف (EN)',
    'homepage.careersDescriptionAr': 'وصف الوظائف (AR)',
    'homepage.settingsSaved': 'تم حفظ إعدادات الصفحة الرئيسية بنجاح.',
    'homepage.saveFailed': 'فشل حفظ إعدادات الصفحة الرئيسية.',
    'homepage.noItems': 'لم يتم العثور على عناصر.',
    'homepage.loadFailed': 'فشل تحميل بيانات الصفحة الرئيسية.',
    'homepage.tab.sectionHeadings': 'عناوين الأقسام',
    'homepage.itemCreated': 'تم إنشاء العنصر بنجاح.',
    'homepage.itemUpdated': 'تم تحديث العنصر بنجاح.',
    'homepage.itemDeleted': 'تم حذف العنصر بنجاح.',
    'homepage.sectionUpdated': 'تم تحديث القسم بنجاح.',
    'homepage.sectionDeleted': 'تم حذف القسم بنجاح.',
    'homepage.invalidSectionKey': 'مفتاح قسم غير صالح.',
    'homepage.duplicateSectionKey': 'مفتاح القسم موجود بالفعل.',

    // User management
    'users.title': 'إدارة المستخدمين',
    'users.subtitle': 'إدارة مستخدمي لوحة التحكم والأدوار والصلاحيات',
    'users.createUser': 'إنشاء مستخدم',
    'users.editUser': 'تعديل المستخدم',
    'users.resetPassword': 'إعادة تعيين كلمة المرور',
    'users.activate': 'تنشيط',
    'users.deactivate': 'إلغاء التنشيط',
    'users.confirmDeactivate': 'هل أنت متأكد أنك تريد إلغاء تنشيط هذا المستخدم؟ سيفقد الوصول إلى لوحة التحكم فوراً.',
    'users.confirmActivate': 'هل أنت متأكد أنك تريد تنشيط هذا المستخدم؟',
    'users.confirmReset': 'هل أنت متأكد أنك تريد إعادة تعيين كلمة مرور هذا المستخدم؟',
    'users.noUsers': 'لم يتم العثور على مستخدمين.',
    'users.loadFailed': 'فشل تحميل المستخدمين.',
    'users.name': 'الاسم',
    'users.actions': 'إجراءات',
    'users.you': '(أنت)',
    'users.allRoles': 'جميع الأدوار',
    'users.allStatuses': 'جميع الحالات',
    'users.active': 'نشط',
    'users.inactive': 'غير نشط',
    'users.created': 'تم إنشاء المستخدم بنجاح.',
    'users.updated': 'تم تحديث المستخدم بنجاح.',
    'users.activated': 'تم تنشيط المستخدم بنجاح.',
    'users.deactivated': 'تم إلغاء تنشيط المستخدم بنجاح.',
    'users.passwordReset': 'تم إعادة تعيين كلمة المرور بنجاح.',
    'users.createFailed': 'فشل إنشاء المستخدم.',
    'users.updateFailed': 'فشل تحديث المستخدم.',
    'users.activateFailed': 'فشل تنشيط المستخدم.',
    'users.deactivateFailed': 'فشل إلغاء تنشيط المستخدم.',
    'users.resetFailed': 'فشل إعادة تعيين كلمة المرور.',
    'users.roleSuperAdmin': 'مدير عام',
    'users.roleAdmin': 'مدير',
    'users.roleContentManager': 'مدير المحتوى',
    'users.roleEditor': 'محرر',
    'users.roleMarketingManager': 'مدير التسويق',
    'users.roleMarketingSeo': 'التسويق / SEO',
    'users.roleRecruiter': 'مسؤول التوظيف',
    'users.roleSupportAgent': 'وكيل الدعم',
    'users.roleSupportRecruiter': 'الدعم / التوظيف',
    'users.roleLmsAdmin': 'مدير LMS',
    'users.roleFinanceSales': 'المالية / المبيعات',
    'form.username': 'اسم المستخدم',
    'form.password': 'كلمة المرور',
    'form.passwordConfirm': 'تأكيد كلمة المرور',
    'form.role': 'الدور',
    'form.status': 'الحالة',
    'form.dateJoined': 'تاريخ الانضمام',
    'form.lastLogin': 'آخر تسجيل دخول',

    // Dashboard
    'dash.welcome': 'مرحباً',
    'dash.quickActions': 'إجراءات سريعة',
    'dash.recentActivity': 'النشاط الأخير',
    'dash.recentSubmissions': 'طلبات التواصل الأخيرة',
    'dash.stats': 'الإحصائيات',
    'dash.total': 'المجموع',
    'dash.active': 'نشط',
    'dash.featured': 'مميز',
    'dash.draft': 'مسودة',
    'dash.published': 'منشور',
    'dash.archived': 'مؤرشف',
    'dash.expired': 'منتهي',
    'dash.new': 'جديد',
    'dash.onHomepage': 'على الصفحة الرئيسية',
    'dash.media': 'أصول الوسائط',
    'dash.images': 'صور',
    'dash.documents': 'مستندات',
    'dash.users': 'المستخدمون',
    'dash.inactive': 'غير نشط',
    'dash.byRole': 'حسب الدور',
    'dash.highPriority': 'أولوية عالية',
    'dash.recentCount': 'حديث (٧ أيام)',
    'dash.inquiryType': 'نوع الاستفسار',
    'dash.priority': 'الأولوية',
    'dash.noActivity': 'لا يوجد نشاط حديث',
    'dash.noSubmissions': 'لا توجد طلبات حديثة',
    'dash.createInsight': 'إنشاء رؤية',
    'dash.addService': 'إضافة خدمة',
    'dash.addPartner': 'إضافة شريك',
    'dash.addCaseStudy': 'إضافة دراسة حالة',
    'dash.addJob': 'إضافة وظيفة',
    'dash.openContact': 'طلبات التواصل',
    'dash.uploadMedia': 'رفع وسائط',
    'dash.manageUsers': 'إدارة المستخدمين',

    // Forms
    'form.english': 'الإنجليزية',
    'form.arabic': 'العربية',
    'form.title': 'العنوان',
    'form.name': 'الاسم',
    'form.slug': 'المعرّف',
    'form.description': 'الوصف',
    'form.status': 'الحالة',
    'form.priority': 'الأولوية',
    'form.type': 'النوع',
    'form.order': 'ترتيب العرض',
    'form.featured': 'مميز',
    'form.active': 'نشط',
    'form.visible': 'مرئي',
    'form.homepage': 'عرض على الرئيسية',
    'form.seo': 'إعدادات SEO',
    'form.image': 'صورة',
    'form.icon': 'أيقونة',
    'form.logo': 'شعار',
    'form.selectImage': 'اختر صورة',
    'form.removeImage': 'إزالة',
    'form.noImage': 'لا توجد صورة',
    'form.created': 'تاريخ الإنشاء',
    'form.updated': 'تاريخ التحديث',
    'form.publishedAt': 'تاريخ النشر',
    'form.author': 'المؤلف',
    'form.category': 'التصنيف',
    'form.excerpt': 'مقتطف',
    'form.body': 'المحتوى',
    'form.contentType': 'نوع المحتوى',
    'form.readTime': 'وقت القراءة (دقائق)',
    'form.clientName': 'اسم العميل',
    'form.industry': 'القطاع',
    'form.shortDescription': 'وصف مختصر',
    'form.problem': 'المشكلة',
    'form.solution': 'الحل',
    'form.technology': 'التقنية',
    'form.outcome': 'النتائج',
    'form.featuredImage': 'الصورة الرئيسية',
    'form.partnerId': 'معرّف الشريك',
    'form.projectUrl': 'رابط المشروع',
    'form.projectYear': 'سنة المشروع',
    'form.department': 'القسم',
    'form.location': 'الموقع',
    'form.responsibilities': 'المسؤوليات',
    'form.requirements': 'المتطلبات',
    'form.preferredQualifications': 'المؤهلات المفضلة',
    'form.benefits': 'المزايا',
    'form.employmentType': 'نوع التوظيف',
    'form.workplaceType': 'نوع مكان العمل',
    'form.experienceLevel': 'مستوى الخبرة',
    'form.applicationMethod': 'طريقة التقديم',
    'form.applicationEmail': 'بريد التقديم',
    'form.externalApplyUrl': 'رابط التقديم الخارجي',
    'form.postedDate': 'تاريخ النشر',
    'form.closingDate': 'تاريخ الإغلاق',
    'form.assignedTo': 'المُسند إلى',
    'form.internalNotes': 'ملاحظات داخلية',
    'form.ctaUrl': 'رابط الدعوة لاتخاذ إجراء',
    'form.ctaLabel': 'نص الدعوة لاتخاذ إجراء',
    'form.seoTitle': 'عنوان SEO',
    'form.seoDescription': 'وصف SEO',
    'form.seoTitleHint': 'الطول الموصى به: 50-60 حرف',
    'form.seoDescriptionHint': 'الطول الموصى به: 150-160 حرف',
    'form.canonicalUrl': 'تجاوز الرابط الأساسي',
    'form.canonicalUrlHint': 'اتركه فارغاً لاستخدام الرابط الافتراضي',
    'form.openGraph': 'Open Graph',
    'form.ogTitle': 'عنوان OG',
    'form.ogTitleHint': 'يستخدم عنوان SEO إذا كان فارغاً',
    'form.ogDescription': 'وصف OG',
    'form.ogImage': 'صورة OG',
    'form.ogImageHint': 'يستخدم الصورة الرئيسية إذا كانت فارغة',
    'form.robotsDirectives': 'توجيهات الروبوت',
    'form.robotsIndex': 'السماح لمحركات البحث بالفهرسة',
    'form.robotsFollow': 'السماح لمحركات البحث بمتابعة الروابط',
    'form.openInNewTab': 'فتح في تبويب جديد',
    'form.partnerType': 'نوع الشريك',
    'form.websiteUrl': 'رابط الموقع',
    'form.linkType': 'نوع الرابط',
    'form.routeName': 'اسم المسار',
    'form.url': 'رابط',
    'form.anchor': 'مرساة',
    'form.iconCssClass': 'أيقونة (CSS class)',
    'form.iconAsset': 'أصل الأيقونة',
    'form.label': 'التسمية',
    'form.target': 'الهدف',
    'nav.menu': 'قائمة',
    'nav.item': 'عنصر',
    'form.email': 'البريد الإلكتروني',
    'form.firstName': 'الاسم الأول',
    'form.lastName': 'اسم العائلة',
    'form.phone': 'الهاتف',
    'form.company': 'الشركة',
    'form.date': 'التاريخ',
    'form.message': 'الرسالة',
    'contact.inquiryType': 'نوع الاستفسار',

    // Status labels
    'status.new': 'جديد',
    'status.contacted': 'تم التواصل',
    'status.inProgress': 'قيد المعالجة',
    'status.closed': 'مغلق',
    'status.spam': 'مزعج',
    'status.archived': 'مؤرشف',

    // Priority labels
    'priority.low': 'منخفض',
    'priority.medium': 'متوسط',
    'priority.high': 'عالي',
    'priority.urgent': 'عاجل',

    // Leads dashboard
    'leads.title': 'العملاء المحتملون',
    'leads.signIn': 'تسجيل الدخول',
    'leads.loginSubtitle': 'الوصول إلى مساحة عمل إدارة العملاء المحتملين.',
    'leads.loading': 'جاري التحميل…',
    'leads.signingIn': 'جاري تسجيل الدخول…',
    'leads.networkError': 'تعذر الاتصال بالخادم. يرجى التحقق من الاتصال والمحاولة مرة أخرى.',
    'leads.loginFailed': 'فشل تسجيل الدخول.',
    'leads.dashboard': 'لوحة العملاء المحتملين',
    'leads.subtitle': 'إدارة وتحديد أولويات العملاء المحتملين والرد عليهم.',
    'leads.total': 'إجمالي العملاء',
    'leads.new': 'جديد',
    'leads.contacted': 'تم التواصل',
    'leads.itemCount': 'عميل محتمل',
    'leads.itemsCount': 'عملاء محتملون',
    'leads.noLeadsFiltered': 'لا توجد عملاء مطابقة للفلتر. امسح الفلتر للبدء من جديد.',
    'leads.closed': 'مغلق',
    'leads.allStatuses': 'كل الحالات',
    'leads.allPriorities': 'كل الأولويات',
    'leads.allTypes': 'كل الأنواع',
    'leads.openDetail': 'فتح',
    'leads.copyEmail': 'نسخ البريد',
    'leads.emailCopied': 'تم النسخ!',
    'leads.openEmailClient': 'فتح في عميل البريد',
    'leads.noLeads': 'لم يتم العثور على عملاء محتملين.',
    'leads.loadFailed': 'فشل تحميل العملاء المحتملين.',
    'leads.notFound': 'العميل المحتمل غير موجود.',
    'leads.backToLeads': 'العودة إلى القائمة',
    'leads.contactInfo': 'معلومات الاتصال',
    'leads.message': 'الرسالة',
    'leads.source': 'المصدر',
    'leads.language': 'اللغة',
    'leads.inquiryType': 'نوع الاستفسار',
    'leads.markSpam': 'تحديد كرسالة مزعجة',
    'leads.markedSpam': 'تم التحديد كرسالة مزعجة.',
    'leads.archive': 'أرشفة',
    'leads.archived': 'تمت الأرشفة.',
    'leads.confirmSpam': 'هل أنت متأكد من تحديد "{name}" كرسالة مزعجة؟ يمكن التراجع عن ذلك بتغيير الحالة.',
    'leads.confirmArchive': 'هل أنت متأكد من أرشفة "{name}"؟ العملاء المؤرشفون لا يظهرون في العرض الافتراضي.',
    'leads.copyFailed': 'فشل نسخ البريد الإلكتروني.',
    'leads.jobTitle': 'المسمى الوظيفي',
    'leads.subject': 'الموضوع',
    'leads.manageLead': 'إدارة العميل',
    'leads.save': 'حفظ التغييرات',
    'leads.saveSuccess': 'تم حفظ التغييرات.',
    'leads.saveFailed': 'فشل حفظ التغييرات.',
    'leads.status': 'الحالة',
    'leads.priority': 'الأولوية',
    'leads.internalNotes': 'ملاحظات داخلية',
    'leads.notesHint': 'ملاحظات خاصة مرئية للفريق فقط.',

    // Confirm
    'confirm.delete.title': 'تأكيد الحذف',
    'confirm.delete.message': 'هل أنت متأكد من حذف "{name}"؟ لا يمكن التراجع عن هذا الإجراء.',
    'confirm.publish.title': 'تأكيد النشر',
    'confirm.publish.message': 'هل أنت متأكد من نشر "{name}"؟',
    'confirm.archive.title': 'تأكيد الأرشفة',
    'confirm.archive.message': 'هل أنت متأكد من أرشفة "{name}"؟',

    // User
    'user.role': 'الدور',
    'user.signOut': 'تسجيل الخروج',
    'user.language': 'اللغة',

    // Common
    'common.loading': 'جارٍ التحميل...',
    'common.accessDenied': 'تم رفض الوصول',
    'common.accessDeniedText': 'لا يمتلك حسابك صلاحية الوصول إلى هذه الوحدة.',
    'common.contactAdmin': 'تواصل مع مسؤول النظام إذا كنت تعتقد أن هذا خطأ.',
    'common.retry': 'إعادة المحاولة',
  },
};

function getCookie(name) {
  const match = document.cookie.match(new RegExp(`(?:^|; )${name}=([^;]*)`));
  return match ? decodeURIComponent(match[1]) : null;
}

function setCookie(name, value, days = 365) {
  const expires = new Date(Date.now() + days * 864e5).toUTCString();
  document.cookie = `${name}=${encodeURIComponent(value)}; expires=${expires}; path=/; SameSite=Lax`;
}

const CMSLanguageContext = createContext(null);

export function CMSLanguageProvider({ children }) {
  const [lang, setLang] = useState(() => getCookie(COOKIE_NAME) || DEFAULT_LANG);

  const dir = lang === 'ar' ? 'rtl' : 'ltr';

  useEffect(() => {
    setCookie(COOKIE_NAME, lang);
    document.documentElement.setAttribute('dir', dir);
  }, [lang, dir]);

  const t = useCallback(
    (key, params) => {
      const dict = translations[lang] || translations[DEFAULT_LANG];
      let str = dict[key] || translations[DEFAULT_LANG][key] || key;
      if (params) {
        for (const [k, v] of Object.entries(params)) {
          str = str.replace(`{${k}}`, String(v));
        }
      }
      return str;
    },
    [lang],
  );

  const toggleLang = useCallback(() => {
    setLang((prev) => (prev === 'en' ? 'ar' : 'en'));
  }, []);

  const value = { lang, dir, t, setLang, toggleLang };

  return <CMSLanguageContext.Provider value={value}>{children}</CMSLanguageContext.Provider>;
}

export function useCMSLang() {
  const ctx = useContext(CMSLanguageContext);
  if (!ctx) {
    throw new Error('useCMSLang must be used within CMSLanguageProvider');
  }
  return ctx;
}
