# Generated by Django 5.2.16 on 2026-07-10 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Human-readable name, e.g. "Main Header".', max_length=120)),
                ('slug', models.SlugField(default='', help_text='Unique code used by the frontend, e.g. "main-header".', max_length=64, unique=True)),
                ('location', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer'), ('mobile', 'Mobile'), ('legal', 'Legal')], default='header', help_text='Menu location hint for the frontend.', max_length=32)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower values appear first in API listings.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive menus are hidden from public APIs.')),
            ],
            options={
                'verbose_name': 'Navigation Menu',
                'verbose_name_plural': 'Navigation Menus',
                'db_table': 'navigation_navigationmenu',
                'ordering': ['location', 'order', 'name'],
                'indexes': [models.Index(fields=['location', 'is_active'], name='navigation__locatio_7c91eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label_en', models.CharField(default='', max_length=120, verbose_name='Label (English)')),
                ('label_ar', models.CharField(blank=True, default='', max_length=120, verbose_name='Label (Arabic)')),
                ('link_type', models.CharField(choices=[('internal', 'Internal page'), ('external', 'External URL'), ('anchor', 'Page anchor'), ('email', 'Email address'), ('phone', 'Phone number')], default='internal', max_length=16)),
                ('url', models.CharField(blank=True, default='', help_text='Internal path or external URL.', max_length=512)),
                ('route_name', models.CharField(blank=True, default='', help_text='Django URL name or frontend route name for internal links.', max_length=120)),
                ('anchor', models.CharField(blank=True, default='', help_text='Anchor target without the #, e.g. "contact".', max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower values appear first.')),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('icon', models.CharField(blank=True, default='', help_text='Optional icon class or identifier.', max_length=120)),
                ('is_visible', models.BooleanField(default=True, help_text='Hidden items are excluded from public APIs.')),
                ('icon_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediaasset')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent item for a two-level dropdown.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='navigation.navigationitem')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='navigation.navigationmenu')),
            ],
            options={
                'verbose_name': 'Navigation Item',
                'verbose_name_plural': 'Navigation Items',
                'db_table': 'navigation_navigationitem',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['menu', 'parent', 'is_visible', 'order'], name='navigation__menu_id_11feef_idx')],
            },
        ),
    ]
