# Generated by Django 5.2.16 on 2026-07-10 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('name_ar', models.CharField(blank=True, max_length=255, verbose_name='Name (Arabic)')),
                ('slug', models.SlugField(help_text='URL-safe identifier.', max_length=255, unique=True, verbose_name='Slug')),
                ('short_description_en', models.TextField(blank=True, verbose_name='Short description (English)')),
                ('short_description_ar', models.TextField(blank=True, verbose_name='Short description (Arabic)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (Arabic)')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower values appear first.', verbose_name='Display order')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive services are hidden from public APIs.', verbose_name='Active')),
                ('show_on_homepage', models.BooleanField(default=False, verbose_name='Show on homepage')),
                ('cta_label_en', models.CharField(blank=True, max_length=120, verbose_name='CTA label (English)')),
                ('cta_label_ar', models.CharField(blank=True, max_length=120, verbose_name='CTA label (Arabic)')),
                ('cta_url', models.CharField(blank=True, max_length=512, verbose_name='CTA URL')),
                ('seo_title_en', models.CharField(blank=True, max_length=255, verbose_name='SEO title (English)')),
                ('seo_title_ar', models.CharField(blank=True, max_length=255, verbose_name='SEO title (Arabic)')),
                ('seo_description_en', models.TextField(blank=True, verbose_name='SEO description (English)')),
                ('seo_description_ar', models.TextField(blank=True, verbose_name='SEO description (Arabic)')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediaasset', verbose_name='Featured image')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediaasset', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'services_service',
                'ordering': ['display_order', 'name_en'],
                'indexes': [models.Index(fields=['display_order', 'name_en'], name='services_order_name_idx'), models.Index(fields=['is_active', 'is_featured', 'display_order'], name='services_active_featured_idx'), models.Index(fields=['is_active', 'show_on_homepage', 'display_order'], name='services_active_homepage_idx')],
            },
        ),
    ]
