# Generated by Django 6.0.2 on 2026-09-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='detail_url_override',
            field=models.CharField(blank=True, help_text='Override the public detail URL for this service. Use for bespoke landing pages (e.g. /services/ai-automation). When blank, the generic /services/<slug> route is used.', max_length=512, verbose_name='Detail URL override'),
        ),
    ]
