# Generated by Django 6.0.2 on 2026-07-10 22:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=120, verbose_name='Name (English)')),
                ('name_ar', models.CharField(blank=True, max_length=120, verbose_name='Name (Arabic)')),
                ('slug', models.SlugField(help_text='URL-safe identifier used by the public API and frontend.', max_length=120, unique=True, verbose_name='Slug')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (Arabic)')),
                ('recipient_email', models.EmailField(blank=True, help_text='Optional. If blank, the Site Setting recipient email is used.', max_length=254, verbose_name='Recipient email override')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower values appear first.', verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive inquiry types are hidden from the public API.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Inquiry Type',
                'verbose_name_plural': 'Inquiry Types',
                'db_table': 'contact_inquirytype',
                'ordering': ['order', 'name_en'],
                'indexes': [models.Index(fields=['is_active', 'order', 'name_en'], name='contact_type_active_order_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Phone')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Company / Organization')),
                ('job_title', models.CharField(blank=True, max_length=120, verbose_name='Job title')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('preferred_contact_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('any', 'Any')], max_length=16, verbose_name='Preferred contact method')),
                ('privacy_consent', models.BooleanField(default=False, help_text='Required to submit the contact form.', verbose_name='Privacy consent')),
                ('source_page', models.CharField(blank=True, help_text='URL path where the form was submitted.', max_length=512, verbose_name='Source page')),
                ('language', models.CharField(blank=True, default='en', max_length=10, verbose_name='Language')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_progress', 'In progress'), ('closed', 'Closed'), ('spam', 'Spam'), ('archived', 'Archived')], db_index=True, default='new', max_length=16, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=16, verbose_name='Priority')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Internal notes')),
                ('email_delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('not_configured', 'Not configured')], db_index=True, default='pending', max_length=16, verbose_name='Email delivery status')),
                ('email_attempted_at', models.DateTimeField(blank=True, null=True, verbose_name='Email attempted at')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Email sent at')),
                ('email_error_summary', models.TextField(blank=True, help_text='Bounded, sanitized summary for admin review. Never a full traceback.', verbose_name='Email error summary')),
                ('recipient_email_used', models.EmailField(blank=True, max_length=254, verbose_name='Recipient email used')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User agent')),
                ('contacted_at', models.DateTimeField(blank=True, null=True, verbose_name='Contacted at')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed at')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to')),
                ('related_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_submissions', to='services.service', verbose_name='Related service')),
                ('inquiry_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='contact.inquirytype', verbose_name='Inquiry type')),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'db_table': 'contact_contactsubmission',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='contact_status_created_idx'), models.Index(fields=['inquiry_type', 'status'], name='contact_type_status_idx'), models.Index(fields=['email', 'created_at'], name='contact_email_created_idx'), models.Index(fields=['email_delivery_status', 'created_at'], name='contact_delivery_created_idx')],
            },
        ),
    ]
