# Generated by Django 6.0.2 on 2026-07-12 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0002_media_asset_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_key', models.CharField(choices=[('hero', 'Hero'), ('foundation', 'Foundation'), ('marquee', 'What We Build'), ('services', 'Services'), ('industries', 'Industries / Solutions'), ('partners', 'Partners'), ('case_studies', 'Case Studies'), ('insights', 'Insights'), ('careers', 'Careers'), ('contact', 'Contact')], max_length=40, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Homepage Section Config',
                'verbose_name_plural': 'Homepage Section Configs',
                'db_table': 'homepage_hompagesectionconfig',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MarqueeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_en', models.CharField(max_length=120)),
                ('title_ar', models.CharField(blank=True, max_length=120)),
                ('description_en', models.CharField(blank=True, max_length=255)),
                ('description_ar', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marquee Item',
                'verbose_name_plural': 'Marquee Items',
                'db_table': 'homepage_marqueeitem',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomepageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_enabled', models.BooleanField(default=True, help_text='Show or hide the hero section.')),
                ('hero_headline_en', models.CharField(blank=True, max_length=200)),
                ('hero_headline_ar', models.CharField(blank=True, max_length=200)),
                ('hero_subheadline_en', models.CharField(blank=True, max_length=300)),
                ('hero_subheadline_ar', models.CharField(blank=True, max_length=300)),
                ('hero_primary_cta_label_en', models.CharField(blank=True, max_length=60)),
                ('hero_primary_cta_label_ar', models.CharField(blank=True, max_length=60)),
                ('hero_primary_cta_target', models.CharField(blank=True, help_text='Internal path (e.g. /services) or anchor (e.g. #services).', max_length=255)),
                ('hero_secondary_cta_label_en', models.CharField(blank=True, max_length=60)),
                ('hero_secondary_cta_label_ar', models.CharField(blank=True, max_length=60)),
                ('hero_secondary_cta_target', models.CharField(blank=True, help_text='Internal path (e.g. /case-studies) or anchor (e.g. #case-studies).', max_length=255)),
                ('hero_show_location_card', models.BooleanField(default=True, help_text='Show or hide the location card in the hero.')),
                ('foundation_enabled', models.BooleanField(default=True)),
                ('foundation_eyebrow_en', models.CharField(blank=True, max_length=80)),
                ('foundation_eyebrow_ar', models.CharField(blank=True, max_length=80)),
                ('foundation_heading_en', models.CharField(blank=True, max_length=200)),
                ('foundation_heading_ar', models.CharField(blank=True, max_length=200)),
                ('foundation_description_en', models.TextField(blank=True)),
                ('foundation_description_ar', models.TextField(blank=True)),
                ('foundation_proof_points_en', models.JSONField(blank=True, default=list, help_text='List of proof point strings (English).')),
                ('foundation_proof_points_ar', models.JSONField(blank=True, default=list, help_text='List of proof point strings (Arabic).')),
                ('foundation_cta_label_en', models.CharField(blank=True, max_length=60)),
                ('foundation_cta_label_ar', models.CharField(blank=True, max_length=60)),
                ('foundation_cta_target', models.CharField(blank=True, max_length=255)),
                ('marquee_heading_en', models.CharField(blank=True, max_length=120)),
                ('marquee_heading_ar', models.CharField(blank=True, max_length=120)),
                ('industries_heading_en', models.CharField(blank=True, max_length=200)),
                ('industries_heading_ar', models.CharField(blank=True, max_length=200)),
                ('industries_description_en', models.TextField(blank=True)),
                ('industries_description_ar', models.TextField(blank=True)),
                ('partners_heading_en', models.CharField(blank=True, max_length=200)),
                ('partners_heading_ar', models.CharField(blank=True, max_length=200)),
                ('partners_description_en', models.TextField(blank=True)),
                ('partners_description_ar', models.TextField(blank=True)),
                ('case_studies_heading_en', models.CharField(blank=True, max_length=200)),
                ('case_studies_heading_ar', models.CharField(blank=True, max_length=200)),
                ('case_studies_description_en', models.TextField(blank=True)),
                ('case_studies_description_ar', models.TextField(blank=True)),
                ('insights_heading_en', models.CharField(blank=True, max_length=200)),
                ('insights_heading_ar', models.CharField(blank=True, max_length=200)),
                ('insights_description_en', models.TextField(blank=True)),
                ('insights_description_ar', models.TextField(blank=True)),
                ('careers_heading_en', models.CharField(blank=True, max_length=200)),
                ('careers_heading_ar', models.CharField(blank=True, max_length=200)),
                ('careers_description_en', models.TextField(blank=True)),
                ('careers_description_ar', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hero_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_media', to='media_library.mediaasset')),
            ],
            options={
                'verbose_name': 'Homepage Settings',
                'verbose_name_plural': 'Homepage Settings',
                'db_table': 'homepage_homepagesettings',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_en', models.CharField(max_length=120)),
                ('title_ar', models.CharField(blank=True, max_length=120)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('focus_areas_en', models.JSONField(blank=True, default=list, help_text='List of focus area strings (English).')),
                ('focus_areas_ar', models.JSONField(blank=True, default=list, help_text='List of focus area strings (Arabic).')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industry_icons', to='media_library.mediaasset')),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
                'db_table': 'homepage_industry',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
