# Generated by Django 6.0.2 on 2026-09-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='training_cta_label_ar',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='training_cta_label_en',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='training_cta_target',
            field=models.CharField(blank=True, help_text='Internal path (e.g. /training) or anchor.', max_length=255),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='training_description_ar',
            field=models.TextField(blank=True, help_text='Description for the Training homepage section (Arabic).'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='training_description_en',
            field=models.TextField(blank=True, help_text='Description for the Training homepage section (English).'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='training_heading_ar',
            field=models.CharField(blank=True, help_text='Heading for the Training homepage section (Arabic).', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='training_heading_en',
            field=models.CharField(blank=True, help_text='Heading for the Training homepage section (English).', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='training_paths',
            field=models.JSONField(blank=True, default=list, help_text='Training path cards for the homepage section. Each item: {key, label_en, label_ar, description_en, description_ar, cta_label_en, cta_label_ar, url}.'),
        ),
    ]
