# Generated by Django 6.0.2 on 2026-09-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_training_offers_section_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesectionconfig',
            name='section_key',
            field=models.CharField(choices=[('hero', 'Hero'), ('foundation', 'Foundation'), ('marquee', 'What We Build'), ('services', 'Services'), ('industries', 'Industries / Solutions'), ('training_education', 'Training Education'), ('training_offers', 'Training Offers'), ('partners', 'Partners'), ('case_studies', 'Case Studies'), ('insights', 'Insights'), ('careers', 'Careers'), ('contact', 'Contact')], max_length=40, unique=True),
        ),
    ]
