# Generated by Django 6.0.2 on 2026-07-10 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_ar', models.CharField(blank=True, max_length=255, verbose_name='Title (Arabic)')),
                ('slug', models.SlugField(help_text='URL-safe identifier.', max_length=255, unique=True, verbose_name='Slug')),
                ('content_type', models.CharField(choices=[('insight', 'Insight'), ('article', 'Article'), ('news', 'News'), ('announcement', 'Announcement')], default='insight', max_length=32, verbose_name='Content type')),
                ('excerpt_en', models.TextField(blank=True, verbose_name='Excerpt (English)')),
                ('excerpt_ar', models.TextField(blank=True, verbose_name='Excerpt (Arabic)')),
                ('body_en', models.TextField(blank=True, verbose_name='Body (English)')),
                ('body_ar', models.TextField(blank=True, verbose_name='Body (Arabic)')),
                ('category_en', models.CharField(blank=True, max_length=120, verbose_name='Category (English)')),
                ('category_ar', models.CharField(blank=True, max_length=120, verbose_name='Category (Arabic)')),
                ('author_name_en', models.CharField(blank=True, max_length=120, verbose_name='Author name (English)')),
                ('author_name_ar', models.CharField(blank=True, max_length=120, verbose_name='Author name (Arabic)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Only published articles are visible to the public.', max_length=16, verbose_name='Status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published at')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('show_on_homepage', models.BooleanField(default=False, verbose_name='Show on homepage')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower values appear first.', verbose_name='Display order')),
                ('read_time_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Read time (minutes)')),
                ('seo_title_en', models.CharField(blank=True, max_length=255, verbose_name='SEO title (English)')),
                ('seo_title_ar', models.CharField(blank=True, max_length=255, verbose_name='SEO title (Arabic)')),
                ('seo_description_en', models.TextField(blank=True, verbose_name='SEO description (English)')),
                ('seo_description_ar', models.TextField(blank=True, verbose_name='SEO description (Arabic)')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediaasset', verbose_name='Featured image')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'db_table': 'insights_article',
                'ordering': ['display_order', '-published_at', 'title_en'],
                'indexes': [models.Index(fields=['status', 'is_featured', 'display_order'], name='insights_status_featured_idx'), models.Index(fields=['status', 'show_on_homepage', 'display_order'], name='insights_status_homepage_idx'), models.Index(fields=['content_type', 'status', 'published_at'], name='insights_type_status_date_idx')],
            },
        ),
    ]
