# Generated by Django 6.0.2 on 2026-07-12 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
        ('media_library', '0002_media_asset_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Override the canonical URL for this article. Leave blank to use the default.', verbose_name='Canonical URL override'),
        ),
        migrations.AddField(
            model_name='article',
            name='og_description_ar',
            field=models.TextField(blank=True, verbose_name='Open Graph description (Arabic)'),
        ),
        migrations.AddField(
            model_name='article',
            name='og_description_en',
            field=models.TextField(blank=True, verbose_name='Open Graph description (English)'),
        ),
        migrations.AddField(
            model_name='article',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='OG image for social sharing. Falls back to featured image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediaasset', verbose_name='Open Graph image'),
        ),
        migrations.AddField(
            model_name='article',
            name='og_title_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='Open Graph title (Arabic)'),
        ),
        migrations.AddField(
            model_name='article',
            name='og_title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Open Graph title (English)'),
        ),
        migrations.AddField(
            model_name='article',
            name='robots_follow',
            field=models.BooleanField(default=True, verbose_name='Allow search engines to follow links'),
        ),
        migrations.AddField(
            model_name='article',
            name='robots_index',
            field=models.BooleanField(default=True, verbose_name='Allow search engines to index'),
        ),
    ]
