"""Public API views for Training & Education programs."""
import hmac
from datetime import timedelta

from django.conf import settings
from django.db import IntegrityError, transaction
from django.db.models import Prefetch
from django.utils import timezone
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from rest_framework.views import APIView

from apps.activity_logs.services import log_activity

from .models import (
    Certificate,
    OfferCampaign,
    OfferItem,
    Program,
    ProgramLanding,
    ProgramModule,
    StarterCampaignConfig,
    StarterLandingPage,
    TrainingRegistration,
)
from .services import send_registration_confirmation
from .serializers import (
    CertificateVerificationSerializer,
    GoogleFormRegistrationSerializer,
    ProgramDetailSerializer,
    ProgramListSerializer,
    PublicOfferCampaignSerializer,
    PublicStarterCampaignConfigSerializer,
    WebsiteRegistrationSerializer,
)


class ProgramListView(APIView):
    """
    GET /api/v1/training/programs/
    Return all active programs, optionally filtered by branch.
    """
    permission_classes = [AllowAny]

    def get(self, request):
        qs = Program.objects.filter(status=Program.STATUS_ACTIVE).select_related(
            'image', 'landing'
        ).order_by('display_order', 'title_en')

        branch = request.query_params.get('branch')
        if branch and branch in dict(Program.BRANCH_CHOICES):
            qs = qs.filter(branch=branch)

        serializer = ProgramListSerializer(qs, many=True, context={'request': request})
        return Response(serializer.data)


class ProgramDetailView(APIView):
    """
    GET /api/v1/training/programs/<slug>/
    Return a single active program by slug with full landing page data.
    """
    permission_classes = [AllowAny]

    def get(self, request, slug):
        try:
            program = Program.objects.prefetch_related(
                Prefetch(
                    'curriculum_modules',
                    queryset=ProgramModule.objects.filter(is_published=True).order_by('display_order', 'id'),
                ),
                'curriculum_modules__topics',
                'program_faqs',
                'program_testimonials',
                'program_instructors__instructor__image',
            ).select_related('image', 'landing', 'landing__og_image').get(
                slug=slug, status=Program.STATUS_ACTIVE
            )
        except Program.DoesNotExist:
            return Response({'detail': 'Not found.'}, status=404)

        serializer = ProgramDetailSerializer(program, context={'request': request})
        return Response(serializer.data)


class ProgramPreviewView(APIView):
    """
    GET /api/v1/training/programs/<slug>/preview/?token=<signed_token>
    Return a program (including draft) by slug if the signed preview token is valid.

    Tokens are short-lived (10 minutes), signed with Django's SECRET_KEY,
    and bound to the program slug. They are NOT stored in the database.
    Tokens can only be generated by authenticated CMS users via the CMS API.
    """
    permission_classes = [AllowAny]

    def get(self, request, slug):
        token = request.query_params.get('token', '').strip()
        if not token:
            return Response({'detail': 'Preview token required.'}, status=403)

        # Verify the signed token
        from .preview_service import is_preview_token_valid
        if not is_preview_token_valid(token, slug):
            return Response({'detail': 'Invalid or expired preview token.'}, status=403)

        try:
            program = Program.objects.prefetch_related(
                'curriculum_modules__topics',
                'program_faqs',
                'program_testimonials',
                'program_instructors__instructor__image',
            ).select_related('image', 'landing').get(slug=slug)
        except Program.DoesNotExist:
            return Response({'detail': 'Not found.'}, status=404)

        serializer = ProgramDetailSerializer(program, context={'request': request})
        return Response(serializer.data)


class AppsScriptSubmissionView(APIView):
    """Secure endpoint for Google Apps Script form submission webhooks."""

    permission_classes = [AllowAny]
    authentication_classes = []
    throttle_scope = 'apps_script_submission'

    def post(self, request):
        provided_secret = request.headers.get('X-Apps-Script-Secret', '')
        expected_secret = getattr(settings, 'APPS_SCRIPT_SECRET', '') or ''

        if not provided_secret or not expected_secret:
            return Response(
                {'detail': 'Authentication required.', 'code': 'auth_required'},
                status=401,
            )
        if not hmac.compare_digest(provided_secret, expected_secret):
            return Response(
                {'detail': 'Invalid secret.', 'code': 'invalid_secret'},
                status=401,
            )

        form_key = request.data.get('form_key', '').strip()
        program = Program.objects.filter(external_form_key=form_key).first() if form_key else None
        if not program:
            return Response(
                {'detail': 'Invalid form configuration.', 'code': 'invalid_form_configuration'},
                status=400,
            )

        external_id = request.data.get('external_submission_id', '')
        existing = TrainingRegistration.objects.filter(
            source=TrainingRegistration.SOURCE_GOOGLE_FORM,
            external_submission_id=external_id,
        ).first() if external_id else None
        if existing:
            if existing.program_id != program.id:
                return Response(
                    {'detail': 'Submission identifier conflict.', 'code': 'submission_conflict'},
                    status=409,
                )
            return Response({
                'id': existing.id,
                'external_submission_id': existing.external_submission_id,
                'status': existing.status,
                'created_at': existing.created_at,
                'is_new': False,
            })

        serializer = GoogleFormRegistrationSerializer(data=request.data, context={'request': request})
        if not serializer.is_valid():
            return Response(serializer.errors, status=400)
        try:
            with transaction.atomic():
                registration = serializer.save()
        except IntegrityError:
            existing = TrainingRegistration.objects.filter(
                source=TrainingRegistration.SOURCE_GOOGLE_FORM,
                external_submission_id=external_id,
                program=program,
            ).first()
            if not existing:
                raise
            return Response({
                'id': existing.id,
                'external_submission_id': existing.external_submission_id,
                'status': existing.status,
                'created_at': existing.created_at,
                'is_new': False,
            })

        log_activity(
            action='create', module='training_registrations', request=request,
            object_instance=registration,
            description='training.google_form.submission_created',
            metadata={
                'external_submission_id': registration.external_submission_id,
                'program_id': registration.program_id,
                'source': registration.source,
            },
        )
        return Response({
            'id': registration.id,
            'external_submission_id': registration.external_submission_id,
            'status': registration.status,
            'created_at': registration.created_at,
            'is_new': True,
        }, status=201)


class WebsiteRegistrationView(APIView):
    """POST /api/v1/training/programs/<slug>/register/
    Public endpoint for native website registration form submissions.

    Features:
    - Honeypot field (website_field) to block bots
    - Privacy policy consent required
    - Registration open/closed/deadline/capacity checks (server-side)
    - UTM attribution capture (no PII in URLs)
    - Idempotency via email+program, or phone+program when Starter email is blank
    - Rate limited via DRF throttle
    - No PII in activity logs
    """

    permission_classes = [AllowAny]
    authentication_classes = []
    throttle_scope = 'website_registration'

    def post(self, request, slug):
        program = Program.objects.filter(slug=slug).first()
        if not program:
            return Response(
                {'detail': 'Course not found.', 'code': 'not_found'},
                status=404,
            )

        serializer = WebsiteRegistrationSerializer(
            data=request.data, context={'request': request, 'program': program}
        )
        if not serializer.is_valid():
            return Response(serializer.errors, status=400)

        # Idempotency: check for existing registration with the same contact identity and program within 24h
        email = serializer.validated_data.get('email', '').strip().lower()
        phone = serializer.validated_data.get('phone', '')
        identity_filter = {'email_normalized': email} if email else {
            'phone_normalized': ''.join(char for char in phone if char.isdigit()),
        }
        existing = TrainingRegistration.objects.filter(
            program=program,
            submitted_at__gte=timezone.now() - timedelta(hours=24),
            **identity_filter,
        ).exclude(status=TrainingRegistration.STATUS_CANCELLED).first()

        if existing:
            return Response({
                'id': existing.id,
                'status': existing.status,
                'is_new': False,
                'message': 'You have already registered for this course.',
            }, status=200)

        try:
            with transaction.atomic():
                registration = serializer.save()
        except IntegrityError:
            return Response({
                'detail': 'Duplicate submission detected.',
                'code': 'duplicate',
            }, status=409)

        # Log without PII
        log_activity(
            action='create', module='training_registrations', request=request,
            object_instance=registration,
            description='training.website.registration_created',
            metadata={
                'program_id': registration.program_id,
                'source': registration.source,
                'utm_source': registration.utm_source,
                'utm_medium': registration.utm_medium,
                'utm_campaign': registration.utm_campaign,
            },
        )

        # Queue confirmation email AFTER the transaction commits so the
        # registration is durably saved before any email is attempted.
        # Email failure is caught inside the service and never rolls back
        # the registration or alters this response.
        registration_pk = registration.pk
        transaction.on_commit(
            lambda: send_registration_confirmation(
                TrainingRegistration.objects.select_related('program').get(pk=registration_pk),
                request=request,
            )
        )

        return Response({
            'id': registration.id,
            'status': registration.status,
            'is_new': True,
            'message': 'Registration received successfully.',
        }, status=201)


class CertificateVerifyView(APIView):
    """Public certificate verification by stable reference.

    GET /api/v1/training/certificates/<reference>/verify/
    Returns only non-PII fields. Rate limited to prevent enumeration.
    Draft certificates are never visible to the public.
    """

    permission_classes = [AllowAny]
    throttle_scope = 'certificate_verify'

    def get(self, request, reference):
        # Exact match only — no partial search to prevent enumeration
        try:
            certificate = Certificate.objects.select_related(
                'training_registration', 'training_registration__program',
                'program', 'media_asset',
            ).get(
                reference=reference,
                status__in=[Certificate.STATUS_ISSUED, Certificate.STATUS_REVOKED],
            )
        except Certificate.DoesNotExist:
            # Generic not found — don't reveal whether reference exists
            return Response(
                {'detail': 'Certificate not found.', 'code': 'not_found'},
                status=404,
            )

        serializer = CertificateVerificationSerializer(certificate, context={'request': request})
        return Response(serializer.data)


class OfferListView(APIView):
    """GET /api/v1/training/offers/

    Public endpoint returning active offer campaigns with their active items.

    Visibility rules (defense in depth):
    - Only campaigns passing active_now() (is_active + schedule window) are returned.
    - Only items with is_active=True and an active program are returned.
    - promo_price is only serialized for items with show_promo_price_publicly=True.

    Query efficiency: campaigns and their items are fetched with two queries
    (select_related on program/image/landing; prefetch of filtered items),
    avoiding N+1 access to campaign defaults from each item.
    """
    permission_classes = [AllowAny]

    def get(self, request):
        item_queryset = OfferItem.objects.filter(
            is_active=True,
            program__status=Program.STATUS_ACTIVE,
        ).select_related(
            'campaign', 'program', 'program__image', 'program__landing',
        ).order_by('display_order', 'id')

        campaigns = (
            OfferCampaign.objects.active_now()
            .prefetch_related(Prefetch('items', queryset=item_queryset, to_attr='public_items'))
            .order_by('priority', 'start_date', 'id')
        )

        serializer = PublicOfferCampaignSerializer(campaigns, many=True, context={'request': request})
        return Response(serializer.data)


class StarterCampaignConfigView(APIView):
    """GET /api/v1/training/starter-form-config/

    Public read-only endpoint returning the shared Starter campaign form
    configuration. Used by the public Starter registration page to render
    CMS-controlled form title/description/button/success/closed messages.

    Returns defaults (created on first access) if no config exists.
    Permission: AllowAny — this is public marketing content, no PII.
    """

    permission_classes = [AllowAny]

    def get(self, request):
        config = StarterCampaignConfig.get_current()
        serializer = PublicStarterCampaignConfigSerializer(config)
        return Response(serializer.data)


class StarterLandingPageView(APIView):
    """GET /api/v1/training/starter-page/

    Public read-only endpoint returning the PUBLISHED section payload for
    the Starter campaign landing page. Draft data, revisions and staff
    metadata are never exposed here. Falls back to the compiled default
    sections when no page row exists so the public page never breaks.
    """

    permission_classes = [AllowAny]

    def get(self, request):
        from .landing_sections import default_sections
        page = StarterLandingPage.objects.filter(slug=StarterLandingPage.SLUG).first()
        sections = page.published_sections if page and page.published_sections else default_sections()
        return Response({'sections': sections})


class StarterLandingPagePreviewView(APIView):
    """GET /api/v1/training/starter-page/preview/?token=<signed_token>

    Returns the DRAFT section payload when a valid CMS-generated preview
    token is supplied. Tokens are short-lived, signed, and bound to the
    starter landing slug (see preview_service). Used only by the shared
    renderer in preview mode — submission stays inert on the client.
    """

    permission_classes = [AllowAny]

    def get(self, request):
        from .landing_sections import default_sections
        from .preview_service import is_preview_token_valid

        token = request.query_params.get('token', '').strip()
        if not token or not is_preview_token_valid(token, StarterLandingPage.SLUG):
            return Response({'detail': 'Invalid or expired preview token.'}, status=403)

        page = StarterLandingPage.objects.filter(slug=StarterLandingPage.SLUG).first()
        sections = page.draft_sections if page and page.draft_sections else default_sections()
        return Response({'sections': sections, 'preview': True})
