# Generated by Django 5.2.16 on 2026-08-18 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0002_media_asset_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_ar', models.CharField(blank=True, max_length=255, verbose_name='Title (Arabic)')),
                ('short_description_en', models.TextField(blank=True, verbose_name='Short Description (English)')),
                ('short_description_ar', models.TextField(blank=True, verbose_name='Short Description (Arabic)')),
                ('overview_en', models.TextField(blank=True, verbose_name='Overview (English)')),
                ('overview_ar', models.TextField(blank=True, verbose_name='Overview (Arabic)')),
                ('branch', models.CharField(choices=[('professional', 'Professional Training'), ('secondary', 'Secondary / Baccalaureate Education')], db_index=True, default='secondary', max_length=32, verbose_name='Branch')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16, verbose_name='Status')),
                ('audience_levels', models.JSONField(blank=True, default=list, help_text='List of audience level identifiers, e.g. ["first_secondary", "second_secondary"]', verbose_name='Audience Levels')),
                ('modules_en', models.JSONField(blank=True, default=list, help_text='List of module titles or objects', verbose_name='Modules/Curriculum (English)')),
                ('modules_ar', models.JSONField(blank=True, default=list, verbose_name='Modules/Curriculum (Arabic)')),
                ('skills_en', models.JSONField(blank=True, default=list, verbose_name='Skills (English)')),
                ('skills_ar', models.JSONField(blank=True, default=list, verbose_name='Skills (Arabic)')),
                ('learning_outcomes_en', models.JSONField(blank=True, default=list, verbose_name='Learning Outcomes (English)')),
                ('learning_outcomes_ar', models.JSONField(blank=True, default=list, verbose_name='Learning Outcomes (Arabic)')),
                ('practical_project_en', models.TextField(blank=True, verbose_name='Practical Project (English)')),
                ('practical_project_ar', models.TextField(blank=True, verbose_name='Practical Project (Arabic)')),
                ('duration_en', models.CharField(blank=True, max_length=120, verbose_name='Duration (English)')),
                ('duration_ar', models.CharField(blank=True, max_length=120, verbose_name='Duration (Arabic)')),
                ('format_en', models.CharField(blank=True, max_length=120, verbose_name='Format (English)')),
                ('format_ar', models.CharField(blank=True, max_length=120, verbose_name='Format (Arabic)')),
                ('schedule_en', models.TextField(blank=True, verbose_name='Schedule (English)')),
                ('schedule_ar', models.TextField(blank=True, verbose_name='Schedule (Arabic)')),
                ('cta_text_en', models.CharField(blank=True, max_length=120, verbose_name='CTA Text (English)')),
                ('cta_text_ar', models.CharField(blank=True, max_length=120, verbose_name='CTA Text (Arabic)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_programs', to='media_library.mediaasset', verbose_name='Cover Image')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'db_table': 'training_program',
                'ordering': ['display_order', 'title_en'],
                'indexes': [models.Index(fields=['branch', 'status'], name='training_branch_status_idx'), models.Index(fields=['display_order'], name='training_order_idx')],
            },
        ),
    ]
