# Generated by Django 6.0.2 on 2026-08-28 03:00
# Consolidated schema migration: adds registration fields to Program,
# creates TrainingRegistration and Certificate models.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_media_asset_fields'),
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ── Program registration fields ──────────────────────────────────
        migrations.AddField(
            model_name='program',
            name='external_form_key',
            field=models.CharField(
                blank=True, db_index=True,
                help_text='Stable identifier mapping an external form to this program; it is not a secret.',
                max_length=64, null=True, unique=True,
                verbose_name='External Form Key',
            ),
        ),
        migrations.AddField(
            model_name='program',
            name='maximum_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum Capacity'),
        ),
        migrations.AddField(
            model_name='program',
            name='registration_closed_cta_text_ar',
            field=models.CharField(blank=True, max_length=120, verbose_name='Registration Closed CTA Text (Arabic)'),
        ),
        migrations.AddField(
            model_name='program',
            name='registration_closed_cta_text_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Registration Closed CTA Text (English)'),
        ),
        migrations.AddField(
            model_name='program',
            name='registration_cta_text_ar',
            field=models.CharField(blank=True, max_length=120, verbose_name='Registration CTA Text (Arabic)'),
        ),
        migrations.AddField(
            model_name='program',
            name='registration_cta_text_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Registration CTA Text (English)'),
        ),
        migrations.AddField(
            model_name='program',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Registration Deadline'),
        ),
        migrations.AddField(
            model_name='program',
            name='registration_open',
            field=models.BooleanField(default=False, verbose_name='Registration Open'),
        ),
        migrations.AddField(
            model_name='program',
            name='registration_success_cta_text_ar',
            field=models.CharField(blank=True, max_length=255, verbose_name='Registration Success CTA Text (Arabic)'),
        ),
        migrations.AddField(
            model_name='program',
            name='registration_success_cta_text_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Registration Success CTA Text (English)'),
        ),
        migrations.AddField(
            model_name='program',
            name='registration_url',
            field=models.URLField(blank=True, verbose_name='Registration URL'),
        ),
        # ── TrainingRegistration ─────────────────────────────────────────
        migrations.CreateModel(
            name='TrainingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(
                    choices=[('google_form', 'Google Form'), ('cms_manual', 'CMS Manual')],
                    db_index=True, default='cms_manual', max_length=32, verbose_name='Source',
                )),
                ('external_submission_id', models.CharField(
                    blank=True, db_index=True,
                    help_text='Idempotency key from the external source (e.g. Google Forms response ID).',
                    max_length=255, verbose_name='External Submission ID',
                )),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Phone')),
                ('national_id', models.CharField(blank=True, max_length=40, verbose_name='National ID / Iqama')),
                ('college_or_school', models.CharField(blank=True, max_length=255, verbose_name='College or School')),
                ('academic_year', models.CharField(blank=True, max_length=120, verbose_name='Academic Year')),
                ('preferred_language', models.CharField(blank=True, default='en', max_length=10, verbose_name='Preferred Language')),
                ('notes', models.TextField(blank=True, verbose_name='Applicant Notes')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Internal Notes')),
                ('email_normalized', models.EmailField(blank=True, db_index=True, max_length=255, verbose_name='Normalized Email')),
                ('phone_normalized', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Normalized Phone')),
                ('status', models.CharField(
                    choices=[
                        ('new', 'New'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'),
                        ('rejected', 'Rejected'), ('enrolled', 'Enrolled'),
                        ('completed', 'Completed'), ('cancelled', 'Cancelled'),
                    ],
                    db_index=True, default='new', max_length=16, verbose_name='Status',
                )),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('review_notes', models.TextField(blank=True, verbose_name='Review Notes')),
                ('source_page', models.CharField(blank=True, max_length=512, verbose_name='Source Page')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('program', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='registrations', to='training.program', verbose_name='Program',
                )),
                ('reviewed_by', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='reviewed_registrations',
                    to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By',
                )),
            ],
            options={
                'verbose_name': 'Training Registration',
                'verbose_name_plural': 'Training Registrations',
                'db_table': 'training_trainingregistration',
                'ordering': ['-submitted_at'],
            },
        ),
        # ── Certificate ──────────────────────────────────────────────────
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(
                    choices=[('draft', 'Draft'), ('issued', 'Issued'), ('revoked', 'Revoked')],
                    db_index=True, default='draft', max_length=16, verbose_name='Status',
                )),
                ('reference', models.CharField(db_index=True, editable=False, max_length=64, unique=True, verbose_name='Certificate Reference')),
                ('certificate_number', models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Certificate Number')),
                ('training_start_date', models.DateField(blank=True, null=True, verbose_name='Training Start Date')),
                ('training_end_date', models.DateField(blank=True, null=True, verbose_name='Training End Date')),
                ('grade', models.CharField(blank=True, max_length=120, verbose_name='Grade')),
                ('result', models.CharField(blank=True, max_length=255, verbose_name='Result')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='Issued At')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revoked At')),
                ('revoked_reason', models.TextField(blank=True, verbose_name='Revoked Reason')),
                ('issued_by', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='issued_certificates',
                    to=settings.AUTH_USER_MODEL, verbose_name='Issued By',
                )),
                ('media_asset', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='certificates',
                    to='media_library.mediaasset', verbose_name='Certificate Media Asset',
                )),
                ('revoked_by', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='revoked_certificates',
                    to=settings.AUTH_USER_MODEL, verbose_name='Revoked By',
                )),
                ('training_registration', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='certificate',
                    to='training.trainingregistration', verbose_name='Training Registration',
                )),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'db_table': 'training_certificate',
                'ordering': ['-created_at'],
            },
        ),
        # ── Indexes ──────────────────────────────────────────────────────
        migrations.AddIndex(
            model_name='trainingregistration',
            index=models.Index(fields=['status', 'submitted_at'], name='tr_reg_status_submitted_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingregistration',
            index=models.Index(fields=['program', 'status'], name='tr_reg_program_status_idx'),
        ),
        # ── Constraints ──────────────────────────────────────────────────
        migrations.AddConstraint(
            model_name='trainingregistration',
            constraint=models.UniqueConstraint(
                condition=models.Q(('external_submission_id__gt', '')),
                fields=('source', 'external_submission_id'),
                name='training_reg_unique_external_submission',
            ),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(
                fields=('reference',),
                name='training_cert_unique_reference',
            ),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.CheckConstraint(
                condition=models.Q(('status__in', ['draft', 'revoked']), ('issued_at__isnull', False), _connector='OR'),
                name='training_cert_issued_requires_timestamp',
            ),
        ),
    ]
