# Generated by Django 6.0.2 on 2026-09-03 12:23

import django.core.validators
import django.db.models.deletion
import secrets
from django.db import migrations, models


def _generate_preview_token():
    """Inline preview token generator for migration (frozen, do not change)."""
    return secrets.token_urlsafe(32)


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_media_asset_fields'),
        ('training', '0003_seed_professional_programs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('name_ar', models.CharField(blank=True, max_length=255, verbose_name='Name (Arabic)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Job Title (English)')),
                ('title_ar', models.CharField(blank=True, max_length=255, verbose_name='Job Title (Arabic)')),
                ('bio_en', models.TextField(blank=True, verbose_name='Bio (English)')),
                ('bio_ar', models.TextField(blank=True, verbose_name='Bio (Arabic)')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_images', to='media_library.mediaasset', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructors',
                'db_table': 'training_instructor',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='ProgramLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headline_en', models.CharField(blank=True, max_length=500, verbose_name='Headline (English)')),
                ('headline_ar', models.CharField(blank=True, max_length=500, verbose_name='Headline (Arabic)')),
                ('intro_video_type', models.CharField(choices=[('none', 'No video'), ('uploaded', 'Uploaded file'), ('youtube', 'YouTube')], default='none', max_length=16, verbose_name='Intro Video Type')),
                ('intro_video_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('video_title_en', models.CharField(blank=True, max_length=255, verbose_name='Video Title (English)')),
                ('video_title_ar', models.CharField(blank=True, max_length=255, verbose_name='Video Title (Arabic)')),
                ('quick_facts', models.JSONField(blank=True, default=dict, help_text='Structured quick facts: level, training_mode, language, duration, hours, sessions, start_date, end_date, has_recordings, has_certificate, has_support, practical_nature. Each value is {ar, en} or scalar.', verbose_name='Quick Facts')),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Current Price')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Original Price')),
                ('currency', models.CharField(default='EGP', max_length=8, verbose_name='Currency')),
                ('included_items', models.JSONField(blank=True, default=dict, help_text='{"ar": [...], "en": [...]}', verbose_name='Included Items')),
                ('show_pricing', models.BooleanField(default=True, verbose_name='Show Pricing Section')),
                ('target_audience', models.JSONField(blank=True, default=dict, help_text='{"ar": [...], "en": [...]}', verbose_name='Target Audience')),
                ('prerequisites', models.JSONField(blank=True, default=dict, help_text='{"ar": [...], "en": [...]}', verbose_name='Prerequisites')),
                ('tools', models.JSONField(blank=True, default=dict, help_text='{"ar": [...], "en": [...]}', verbose_name='Tools & Technologies')),
                ('practical_training_en', models.TextField(blank=True, verbose_name='Practical Training (English)')),
                ('practical_training_ar', models.TextField(blank=True, verbose_name='Practical Training (Arabic)')),
                ('final_project_en', models.TextField(blank=True, verbose_name='Final Project (English)')),
                ('final_project_ar', models.TextField(blank=True, verbose_name='Final Project (Arabic)')),
                ('seo_title_en', models.CharField(blank=True, max_length=255, verbose_name='SEO Title (English)')),
                ('seo_title_ar', models.CharField(blank=True, max_length=255, verbose_name='SEO Title (Arabic)')),
                ('seo_meta_description_en', models.TextField(blank=True, verbose_name='SEO Meta Description (English)')),
                ('seo_meta_description_ar', models.TextField(blank=True, verbose_name='SEO Meta Description (Arabic)')),
                ('canonical_slug', models.CharField(blank=True, max_length=255, verbose_name='Canonical Slug')),
                ('seo_noindex', models.BooleanField(default=False, verbose_name='No Index')),
                ('preview_token', models.CharField(default=_generate_preview_token, editable=False, help_text='Short-lived token for authenticated preview of draft programs.', max_length=64, unique=True, verbose_name='Preview Token')),
                ('intro_video_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_intro_videos', to='media_library.mediaasset', verbose_name='Uploaded Video')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_og_images', to='media_library.mediaasset', verbose_name='Open Graph Image')),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landing', to='training.program', verbose_name='Program')),
                ('video_poster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_video_posters', to='media_library.mediaasset', verbose_name='Video Poster')),
            ],
            options={
                'verbose_name': 'Program Landing Page',
                'verbose_name_plural': 'Program Landing Pages',
                'db_table': 'training_programlanding',
            },
        ),
        migrations.CreateModel(
            name='ProgramModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_ar', models.CharField(blank=True, max_length=255, verbose_name='Title (Arabic)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (Arabic)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_modules', to='training.program', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Program Module',
                'verbose_name_plural': 'Program Modules',
                'db_table': 'training_programmodule',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ModuleTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_ar', models.CharField(blank=True, max_length=255, verbose_name='Title (Arabic)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='training.programmodule', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Module Topic',
                'verbose_name_plural': 'Module Topics',
                'db_table': 'training_moduletopic',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_name_en', models.CharField(max_length=255, verbose_name='Student Name (English)')),
                ('student_name_ar', models.CharField(blank=True, max_length=255, verbose_name='Student Name (Arabic)')),
                ('content_en', models.TextField(blank=True, verbose_name='Testimonial (English)')),
                ('content_ar', models.TextField(blank=True, verbose_name='Testimonial (Arabic)')),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('is_approved', models.BooleanField(default=False, help_text='Only approved testimonials appear on public pages.', verbose_name='Approved / Published')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonial_images', to='media_library.mediaasset', verbose_name='Student Photo')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_testimonials', to='training.program', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Program Testimonial',
                'verbose_name_plural': 'Program Testimonials',
                'db_table': 'training_programtestimonial',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_en', models.CharField(max_length=500, verbose_name='Question (English)')),
                ('question_ar', models.CharField(blank=True, max_length=500, verbose_name='Question (Arabic)')),
                ('answer_en', models.TextField(blank=True, verbose_name='Answer (English)')),
                ('answer_ar', models.TextField(blank=True, verbose_name='Answer (Arabic)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_faqs', to='training.program', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Program FAQ',
                'verbose_name_plural': 'Program FAQs',
                'db_table': 'training_programfaq',
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['program', 'display_order'], name='tr_faq_order_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProgramInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_instructors', to='training.instructor', verbose_name='Instructor')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_instructors', to='training.program', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Program Instructor',
                'verbose_name_plural': 'Program Instructors',
                'db_table': 'training_programinstructor',
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['program', 'display_order'], name='tr_instr_order_idx')],
                'constraints': [models.UniqueConstraint(fields=('program', 'instructor'), name='unique_program_instructor')],
            },
        ),
        migrations.AddIndex(
            model_name='programmodule',
            index=models.Index(fields=['program', 'display_order'], name='tr_module_order_idx'),
        ),
        migrations.AddIndex(
            model_name='moduletopic',
            index=models.Index(fields=['module', 'display_order'], name='tr_topic_order_idx'),
        ),
        migrations.AddIndex(
            model_name='programtestimonial',
            index=models.Index(fields=['program', 'is_approved', 'display_order'], name='tr_test_order_idx'),
        ),
    ]
