# Generated by Django 6.0.2 on 2026-09-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_seed_landing_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programlanding',
            name='preview_token',
        ),
    ]
