# Generated by Django 6.0.2 on 2026-09-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_remove_preview_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='programlanding',
            name='fallback_google_form_url',
            field=models.URLField(blank=True, help_text='Shown when the backend form is unavailable. Leave empty to hide.', verbose_name='Fallback Google Form URL'),
        ),
        migrations.AddField(
            model_name='programlanding',
            name='registration_closed_message_ar',
            field=models.TextField(blank=True, default='التسجيل في هذه الدورة مغلق حاليًا.', verbose_name='Closed Message (Arabic)'),
        ),
        migrations.AddField(
            model_name='programlanding',
            name='registration_closed_message_en',
            field=models.TextField(blank=True, default='Registration for this course is currently closed.', verbose_name='Closed Message (English)'),
        ),
        migrations.AddField(
            model_name='programlanding',
            name='registration_form_button_ar',
            field=models.CharField(blank=True, default='إرسال التسجيل', max_length=120, verbose_name='Submit Button (Arabic)'),
        ),
        migrations.AddField(
            model_name='programlanding',
            name='registration_form_button_en',
            field=models.CharField(blank=True, default='Submit Registration', max_length=120, verbose_name='Submit Button (English)'),
        ),
        migrations.AddField(
            model_name='programlanding',
            name='registration_form_description_ar',
            field=models.TextField(blank=True, verbose_name='Form Description (Arabic)'),
        ),
        migrations.AddField(
            model_name='programlanding',
            name='registration_form_description_en',
            field=models.TextField(blank=True, verbose_name='Form Description (English)'),
        ),
        migrations.AddField(
            model_name='programlanding',
            name='registration_form_title_ar',
            field=models.CharField(blank=True, default='سجل في هذه الدورة', max_length=255, verbose_name='Form Title (Arabic)'),
        ),
        migrations.AddField(
            model_name='programlanding',
            name='registration_form_title_en',
            field=models.CharField(blank=True, default='Register for this Course', max_length=255, verbose_name='Form Title (English)'),
        ),
        migrations.AddField(
            model_name='programlanding',
            name='registration_success_message_ar',
            field=models.TextField(blank=True, default='تم استلام تسجيلك. سنتواصل معك قريبًا.', verbose_name='Success Message (Arabic)'),
        ),
        migrations.AddField(
            model_name='programlanding',
            name='registration_success_message_en',
            field=models.TextField(blank=True, default='Your registration has been received. We will contact you soon.', verbose_name='Success Message (English)'),
        ),
        migrations.AddField(
            model_name='programlanding',
            name='show_registration_form',
            field=models.BooleanField(default=True, verbose_name='Show Registration Form'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='landing_page_url',
            field=models.CharField(blank=True, max_length=512, verbose_name='Landing Page URL'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='referrer',
            field=models.CharField(blank=True, max_length=512, verbose_name='HTTP Referrer'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='utm_campaign',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='UTM Campaign'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='utm_content',
            field=models.CharField(blank=True, max_length=255, verbose_name='UTM Content'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='utm_medium',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='UTM Medium'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='utm_source',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='UTM Source'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='utm_term',
            field=models.CharField(blank=True, max_length=255, verbose_name='UTM Term'),
        ),
        migrations.AlterField(
            model_name='trainingregistration',
            name='source',
            field=models.CharField(choices=[('google_form', 'Google Form'), ('cms_manual', 'CMS Manual'), ('website', 'Website Form')], db_index=True, default='cms_manual', max_length=32, verbose_name='Source'),
        ),
    ]
