# Generated by Django 6.0.2 on 2026-09-03 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_media_asset_fields'),
        ('training', '0007_registration_utm_and_form_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Certificate Title'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_type',
            field=models.CharField(choices=[('completion', 'Completion'), ('recognition', 'Recognition')], db_index=True, default='completion', max_length=16, verbose_name='Certificate Type'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='training.program', verbose_name='Program'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Recipient Name'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='recognition_reason',
            field=models.TextField(blank=True, verbose_name='Recognition Reason'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='revoked_reason',
            field=models.TextField(blank=True, verbose_name='Revoked Reason (Internal)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='training_registration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='training.trainingregistration', verbose_name='Training Registration'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('certificate_type', 'completion'), ('training_registration__isnull', False)), models.Q(('certificate_type', 'recognition'), ('recipient_name__gt', '')), _connector='OR'), name='training_cert_type_consistency'),
        ),
    ]
