# Generated by Django 6.0.2 on 2026-09-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_certificate_types_and_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingregistration',
            name='education_status',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Education Status'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='education_status_other',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Education Status (Other — custom text)'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='university',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='University'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='university_other',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='University (Other — custom text)'),
        ),
    ]
