# Generated by Django 5.2.16 on 2026-09-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_education_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, help_text='Manually-designed final certificate PDF. File must not be modified by the application.', null=True, upload_to='certificates/', verbose_name='Certificate File'),
        ),
    ]
