# Generated by Django 5.2.17 on 2026-09-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_certificate_file_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='programlanding',
            name='installments_available',
            field=models.BooleanField(default=False, help_text='Whether installment-based payment is available for this program.', verbose_name='Installments Available'),
        ),
        migrations.AddField(
            model_name='programlanding',
            name='installments_info_ar',
            field=models.TextField(blank=True, default='', help_text='Installment plan details, payment methods, and instructions.', verbose_name='Installments Info (Arabic)'),
        ),
        migrations.AddField(
            model_name='programlanding',
            name='installments_info_en',
            field=models.TextField(blank=True, default='', help_text='Installment plan details, payment methods, and instructions.', verbose_name='Installments Info (English)'),
        ),
        migrations.AddField(
            model_name='programlanding',
            name='mentor_info_ar',
            field=models.TextField(blank=True, default='', help_text='Mentor support, follow-up, and student guidance information.', verbose_name='Mentor & Follow-up Info (Arabic)'),
        ),
        migrations.AddField(
            model_name='programlanding',
            name='mentor_info_en',
            field=models.TextField(blank=True, default='', help_text='Mentor support, follow-up, and student guidance information.', verbose_name='Mentor & Follow-up Info (English)'),
        ),
        migrations.AddField(
            model_name='programlanding',
            name='training_experience_ar',
            field=models.TextField(blank=True, default='', help_text='Shared training experience: live training, recorded sessions, hands-on learning, etc.', verbose_name='Training Experience (Arabic)'),
        ),
        migrations.AddField(
            model_name='programlanding',
            name='training_experience_en',
            field=models.TextField(blank=True, default='', help_text='Shared training experience: live training, recorded sessions, hands-on learning, etc.', verbose_name='Training Experience (English)'),
        ),
    ]
