# Generated by Django 5.2.17 on 2026-09-08 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_media_asset_fields'),
        ('training', '0011_add_installments_mentor_training_experience_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='certificate',
            name='training_cert_type_consistency',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_type',
            field=models.CharField(choices=[('completion', 'Completion'), ('recognition', 'Recognition'), ('instructor', 'Instructor')], db_index=True, default='completion', max_length=16, verbose_name='Certificate Type'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('certificate_type', 'completion'), ('training_registration__isnull', False)), models.Q(('certificate_type', 'recognition'), ('recipient_name__gt', '')), models.Q(('certificate_type', 'instructor'), ('recipient_name__gt', '')), _connector='OR'), name='training_cert_type_consistency'),
        ),
    ]
