# Generated by Django 6.0.2 on 2026-09-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_remove_certificate_training_cert_type_consistency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='branch',
            field=models.CharField(choices=[('professional', 'Professional Training'), ('secondary', 'Secondary / Baccalaureate Education'), ('starter', 'Sidrah Starter Courses'), ('summer', 'Summer Training')], db_index=True, default='secondary', max_length=32, verbose_name='Branch'),
        ),
    ]
