# Generated by Django 6.0.2 on 2026-09-15 16:07

import apps.training.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_alter_program_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_ar', models.CharField(blank=True, max_length=255, verbose_name='Title (Arabic)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (Arabic)')),
                ('badge_en', models.CharField(blank=True, help_text='Default badge shown for offer items that do not override it.', max_length=80, verbose_name='Default Badge (English)')),
                ('badge_ar', models.CharField(blank=True, max_length=80, verbose_name='Default Badge (Arabic)')),
                ('start_date', models.DateTimeField(help_text='Campaign becomes publicly visible at this moment (when active).', verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, help_text='Leave empty for an open-ended campaign.', null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Manual toggle. Public visibility also requires the schedule window to include now.', verbose_name='Active')),
                ('priority', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower values appear first when multiple campaigns are active.', verbose_name='Priority')),
                ('seo_title_en', models.CharField(blank=True, max_length=255, verbose_name='SEO Title (English)')),
                ('seo_title_ar', models.CharField(blank=True, max_length=255, verbose_name='SEO Title (Arabic)')),
                ('seo_description_en', models.TextField(blank=True, verbose_name='SEO Description (English)')),
                ('seo_description_ar', models.TextField(blank=True, verbose_name='SEO Description (Arabic)')),
            ],
            options={
                'verbose_name': 'Offer Campaign',
                'verbose_name_plural': 'Offer Campaigns',
                'db_table': 'training_offercampaign',
                'ordering': ['priority', 'start_date', 'id'],
                'indexes': [models.Index(fields=['is_active', 'start_date', 'end_date'], name='tr_ocamp_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='OfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badge_en', models.CharField(blank=True, help_text='Overrides the campaign default badge for this course.', max_length=80, verbose_name='Badge (English)')),
                ('badge_ar', models.CharField(blank=True, max_length=80, verbose_name='Badge (Arabic)')),
                ('promotional_copy_en', models.TextField(blank=True, help_text='Overrides the campaign description for this course.', verbose_name='Promotional Copy (English)')),
                ('promotional_copy_ar', models.TextField(blank=True, verbose_name='Promotional Copy (Arabic)')),
                ('cta_label_en', models.CharField(blank=True, help_text='Overrides the program default CTA label.', max_length=120, verbose_name='CTA Label (English)')),
                ('cta_label_ar', models.CharField(blank=True, max_length=120, verbose_name='CTA Label (Arabic)')),
                ('cta_url', models.CharField(blank=True, help_text='Defaults to the course landing page. Must be an internal path or https:// URL.', max_length=255, validators=[apps.training.models.validate_offer_cta_url], verbose_name='CTA URL Override')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Display Order')),
                ('promo_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Offers can be promotional without a numeric price.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Promotional Price')),
                ('promo_currency', models.CharField(default='EGP', max_length=8, verbose_name='Promotional Currency')),
                ('show_promo_price_publicly', models.BooleanField(default=False, help_text='When False, the numeric promo price is never serialized by public APIs. Keep False for Professional courses (price shown on inquiry only).', verbose_name='Show Promo Price Publicly')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Allows disabling a single course without ending the campaign.', verbose_name='Active')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='training.offercampaign', verbose_name='Campaign')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_items', to='training.program', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Offer Item',
                'verbose_name_plural': 'Offer Items',
                'db_table': 'training_offeritem',
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['campaign', 'is_active', 'display_order'], name='tr_oitem_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'program'), name='tr_offer_unique_campaign_program')],
            },
        ),
    ]
