# Generated by Django 6.0.2 on 2026-09-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0014_offers_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingregistration',
            name='confirmation_email_attempted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmation Email Attempted At'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='confirmation_email_error_summary',
            field=models.TextField(blank=True, default='', verbose_name='Confirmation Email Error Summary'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='confirmation_email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmation Email Sent At'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='confirmation_email_status',
            field=models.CharField(choices=[('not_attempted', 'Not attempted'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='not_attempted', max_length=20, verbose_name='Confirmation Email Status'),
        ),
    ]
