# Generated by Django 6.0.2 on 2026-09-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0015_trainingregistration_confirmation_email_attempted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingregistration',
            name='acquisition_source',
            field=models.CharField(blank=True, default='', help_text='How the applicant heard about Sidrah (Starter campaign registration).', max_length=20, verbose_name='Acquisition Source'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='acquisition_source_other',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Acquisition Source (Other — custom text)'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='current_level',
            field=models.CharField(blank=True, default='', help_text='Applicant self-assessed level for Starter campaign registration.', max_length=20, verbose_name='Current Level'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='current_status',
            field=models.CharField(blank=True, default='', help_text='Applicant current occupational status for Starter campaign registration.', max_length=20, verbose_name='Current Status'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='current_status_other',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Current Status (Other — custom text)'),
        ),
    ]
