# Generated by Django 5.2.17 on 2026-09-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0016_starter_campaign_registration_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarterCampaignConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show_registration_form', models.BooleanField(default=True, help_text='When disabled, the Starter registration form is hidden on the public campaign page.', verbose_name='Show Registration Form')),
                ('form_title_en', models.CharField(default='Register for a Starter Course', max_length=255, verbose_name='Form Title (English)')),
                ('form_description_en', models.TextField(blank=True, default='Choose your course and fill in your details. We will contact you to complete registration.', verbose_name='Form Description (English)')),
                ('form_button_en', models.CharField(default='Register Now — Start for 99 EGP Only', max_length=120, verbose_name='Submit Button (English)')),
                ('success_message_en', models.TextField(blank=True, default='Thank you for registering! The Sidrah team will contact you to complete the registration process.', verbose_name='Success Message (English)')),
                ('success_note_en', models.TextField(blank=True, default='This is a registration receipt confirmation — not an acceptance, payment, or seat confirmation.', verbose_name='Success Note (English)')),
                ('closed_message_en', models.TextField(blank=True, default='Registration for this course is currently closed.', verbose_name='Closed Message (English)')),
                ('form_title_ar', models.CharField(default='سجّل في كورس Starter', max_length=255, verbose_name='Form Title (Arabic)')),
                ('form_description_ar', models.TextField(blank=True, default='اختر كورسك واملأ البيانات. سنتواصل معك لإكمال التسجيل.', verbose_name='Form Description (Arabic)')),
                ('form_button_ar', models.CharField(default='سجّل الآن — ابدأ بـ99 جنيه فقط', max_length=120, verbose_name='Submit Button (Arabic)')),
                ('success_message_ar', models.TextField(blank=True, default='شكراً لتسجيلك! سيتواصل معك فريق Sidrah لإكمال عملية التسجيل.', verbose_name='Success Message (Arabic)')),
                ('success_note_ar', models.TextField(blank=True, default='هذا تأكيد استلام التسجيل — وليس تأكيد قبول أو دفع أو مقعد مؤكد.', verbose_name='Success Note (Arabic)')),
                ('closed_message_ar', models.TextField(blank=True, default='التسجيل في هذه الدورة مغلق حاليًا.', verbose_name='Closed Message (Arabic)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Only one active config record is used. Activating this record deactivates others.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Starter Campaign Configuration',
                'verbose_name_plural': 'Starter Campaign Configurations',
                'db_table': 'training_startercampaignconfig',
            },
        ),
    ]
