# Generated by Django 5.2.17 on 2026-09-23 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0017_startercampaignconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='track',
            field=models.CharField(blank=True, default='', help_text='Canonical track name used to group related programs in operational reports, e.g. "Data Analysis".', max_length=255, verbose_name='Track'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='enrollment_stage',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('needs_contact', 'Needs Contact'), ('contacted', 'Contacted'), ('follow_up', 'Follow-up Required'), ('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed / Enrolled'), ('cancelled', 'Cancelled')], db_index=True, default='unknown', help_text='Operational follow-up stage. Independent from the training lifecycle status.', max_length=20, verbose_name='Enrollment Stage'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='follow_up_notes',
            field=models.TextField(blank=True, default='', verbose_name='Follow-up Notes'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Contacted At'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='next_follow_up_at',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Next Follow-up At'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Paid Amount'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Payment Date'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('vodafone_cash', 'Vodafone Cash'), ('instapay', 'InstaPay'), ('other', 'Other')], default='', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='payment_notes',
            field=models.TextField(blank=True, default='', verbose_name='Payment Notes'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Payment Reference'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='payment_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('unpaid', 'Unpaid'), ('pending', 'Pending'), ('paid', 'Paid'), ('not_applicable', 'Not Applicable')], db_index=True, default='unknown', help_text='Payment tracking. Historical records default to Unknown.', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='whatsapp_group_added',
            field=models.BooleanField(db_index=True, default=False, verbose_name='WhatsApp Group Added'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='whatsapp_group_added_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='WhatsApp Group Added At'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='whatsapp_group_added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_group_additions', to=settings.AUTH_USER_MODEL, verbose_name='WhatsApp Group Added By'),
        ),
        migrations.AddIndex(
            model_name='trainingregistration',
            index=models.Index(fields=['enrollment_stage', 'submitted_at'], name='tr_reg_stage_submitted_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingregistration',
            index=models.Index(fields=['payment_status', 'submitted_at'], name='tr_reg_payment_submitted_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingregistration',
            index=models.Index(fields=['whatsapp_group_added', 'payment_status'], name='tr_reg_whatsapp_payment_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingregistration',
            index=models.Index(fields=['next_follow_up_at'], name='tr_reg_followup_idx'),
        ),
    ]
