# Generated by Django 6.0.2 on 2026-09-26 22:03
#
# Extended: seeds the singleton StarterLandingPage with the compiled
# default sections so the public page is unchanged until staff publish
# their first edit.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


# FROZEN at authoring time — identical to default_sections() output when
# this migration was approved. Deliberately inlined (no import from
# apps.training.landing_sections) so the migration always seeds the same
# initial content regardless of later renderer/schema changes.
FROZEN_DEFAULT_SECTIONS = [
    {
        'id': 'hero',
        'type': 'hero',
        'enabled': True,
        'props': {
            'badge_en': 'Beginner Course — From Zero',
            'badge_ar': 'كورس للمبتدئين — من الصفر',
            'title_en': 'Start Your Field from Zero with Sidrah Soft',
            'title_ar': 'ابدأ مجالك من الصفر مع Sidrah Soft',
            'tagline_en': '6 weeks · 12 live sessions · 2 per week · from zero',
            'tagline_ar': '6 أسابيع · 12 جلسة مباشرة · جلستين أسبوعيًا · من الصفر',
            'brand_en': 'Sidrah Soft — Enter The Next Era.',
            'brand_ar': 'Sidrah Soft — ادخل الحقبة القادمة.',
            'cta_en': 'Register Now',
            'cta_ar': 'سجّل الآن',
            'price_display': 'shared',
        },
    },
    {
        'id': 'register',
        'type': 'registration_form',
        'enabled': True,
        'props': {},
    },
]


def seed_starter_landing(apps, schema_editor):
    StarterLandingPage = apps.get_model('training', 'StarterLandingPage')
    if not StarterLandingPage.objects.filter(slug='starter-register').exists():
        sections = FROZEN_DEFAULT_SECTIONS
        StarterLandingPage.objects.create(
            slug='starter-register',
            draft_sections=sections,
            published_sections=sections,
            published_at=timezone.now(),
        )


def noop(apps, schema_editor):
    # Keep the page row on reverse — it is live public configuration.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0020_starter_pricing_499'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StarterLandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(default='starter-register', max_length=64, unique=True)),
                ('draft_sections', models.JSONField(blank=True, default=list)),
                ('published_sections', models.JSONField(blank=True, default=list)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starter_landing_publications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Starter Landing Page',
                'verbose_name_plural': 'Starter Landing Pages',
            },
        ),
        migrations.CreateModel(
            name='StarterLandingRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections', models.JSONField(default=list)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='training.starterlandingpage')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starter_landing_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Starter Landing Revision',
                'verbose_name_plural': 'Starter Landing Revisions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(seed_starter_landing, noop),
    ]
