# Generated by Django 6.0.2 on 2026-09-27 01:38

from django.db import migrations, models


def populate_operational_status(apps, schema_editor):
    # Approved business decision: the new CRM operational workflow starts
    # from a clean baseline. EVERY existing registration initializes as
    # 'lead' — no inference from legacy status, enrollment_stage,
    # payment_status, WhatsApp, or follow-up fields. Those historical
    # fields remain untouched and keep their own semantics (legacy status
    # still controls training lifecycle / certificate eligibility).
    TrainingRegistration = apps.get_model('training', 'TrainingRegistration')
    total = TrainingRegistration.objects.all().update(operational_status='lead')
    print(f'\n[0022] operational_status clean baseline: {total} -> lead')


def noop_reverse(apps, schema_editor):
    # Forward migration sets a clean baseline; reversing would discard
    # real staff edits made after rollout, so the reverse is intentionally
    # a no-op (the field drop is handled by the AddField reverse itself).
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0021_starter_landing_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingregistration',
            name='operational_status',
            field=models.CharField(choices=[('lead', 'Lead'), ('contacted', 'Contacted'), ('subscribed', 'Subscribed'), ('cancelled', 'Cancelled')], db_index=True, default='lead', help_text='Primary staff workflow status (lead/contacted/subscribed/cancelled).', max_length=16, verbose_name='Operational Status'),
        ),
        migrations.RunPython(populate_operational_status, noop_reverse),
    ]
