# Generated by Django 6.0.2 on 2026-09-27 03:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0022_starter_operational_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingregistration',
            name='course_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Advertised course price at the time of registration.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Course Price'),
        ),
        migrations.AddField(
            model_name='trainingregistration',
            name='course_price_currency',
            field=models.CharField(blank=True, default='', help_text='Currency of the registration-time course price snapshot.', max_length=8, verbose_name='Course Price Currency'),
        ),
    ]
