# Generated by Django 6.0.2 on 2026-09-09 18:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name for CMS reference', max_length=120)),
                ('title_en', models.CharField(help_text='Public English title', max_length=200)),
                ('title_ar', models.CharField(blank=True, help_text='Public Arabic title', max_length=200)),
                ('description_en', models.TextField(blank=True, help_text='English description shown above fields')),
                ('description_ar', models.TextField(blank=True, help_text='Arabic description shown above fields')),
                ('slug', models.SlugField(help_text='URL-safe identifier', max_length=120, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Inactive forms are not publicly accessible')),
                ('submit_button_en', models.CharField(default='Submit', max_length=60)),
                ('submit_button_ar', models.CharField(blank=True, max_length=60)),
                ('success_message_en', models.TextField(default='Thank you for your submission.')),
                ('success_message_ar', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Form Definition',
                'verbose_name_plural': 'Form Definitions',
                'db_table': 'forms_formdefinition',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(blank=True, db_index=True, help_text='Stable internal key for system fields', max_length=60)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('phone', 'Phone'), ('number', 'Number'), ('textarea', 'Textarea'), ('select', 'Select'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('date', 'Date'), ('url', 'URL')], default='text', max_length=20)),
                ('label_en', models.CharField(max_length=200)),
                ('label_ar', models.CharField(blank=True, max_length=200)),
                ('placeholder_en', models.CharField(blank=True, max_length=200)),
                ('placeholder_ar', models.CharField(blank=True, max_length=200)),
                ('help_text_en', models.CharField(blank=True, max_length=300)),
                ('help_text_ar', models.CharField(blank=True, max_length=300)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_system', models.BooleanField(db_index=True, default=False, help_text='System fields are protected from unsafe CMS operations')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms.formdefinition')),
            ],
            options={
                'verbose_name': 'Form Field',
                'verbose_name_plural': 'Form Fields',
                'db_table': 'forms_formfield',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FormFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Stable internal value stored in submissions', max_length=100)),
                ('label_en', models.CharField(max_length=200)),
                ('label_ar', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='forms.formfield')),
            ],
            options={
                'verbose_name': 'Form Field Option',
                'verbose_name_plural': 'Form Field Options',
                'db_table': 'forms_formfieldoption',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('source_page', models.CharField(blank=True, max_length=512)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('archived', 'Archived')], db_index=True, default='new', max_length=16)),
                ('internal_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms.formdefinition')),
            ],
            options={
                'verbose_name': 'Form Submission',
                'verbose_name_plural': 'Form Submissions',
                'db_table': 'forms_formsubmission',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmissionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(blank=True, db_index=True, max_length=60)),
                ('field_label', models.CharField(blank=True, max_length=200)),
                ('field_type', models.CharField(default='text', max_length=20)),
                ('value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='forms.formsubmission')),
            ],
            options={
                'verbose_name': 'Form Submission Value',
                'verbose_name_plural': 'Form Submission Values',
                'db_table': 'forms_formsubmissionvalue',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FormAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('ai_automation', 'AI Automation Page'), ('contact', 'Contact Page'), ('landing_generic', 'Generic Landing Page')], db_index=True, max_length=60)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='forms.formdefinition')),
            ],
            options={
                'verbose_name': 'Form Assignment',
                'verbose_name_plural': 'Form Assignments',
                'db_table': 'forms_formassignment',
                'ordering': ['target'],
                'indexes': [models.Index(fields=['target', 'is_active'], name='forms_forma_target_c27c9c_idx')],
                'unique_together': {('target', 'is_active')},
            },
        ),
        migrations.AddIndex(
            model_name='formfield',
            index=models.Index(fields=['form', 'display_order'], name='forms_formf_form_id_878799_idx'),
        ),
        migrations.AddIndex(
            model_name='formfield',
            index=models.Index(fields=['form', 'is_active'], name='forms_formf_form_id_ad766d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='formfield',
            unique_together={('form', 'field_key')},
        ),
        migrations.AddIndex(
            model_name='formfieldoption',
            index=models.Index(fields=['field', 'display_order'], name='forms_formf_field_i_6accc7_idx'),
        ),
        migrations.AddIndex(
            model_name='formfieldoption',
            index=models.Index(fields=['field', 'is_active'], name='forms_formf_field_i_eb2513_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='formfieldoption',
            unique_together={('field', 'value')},
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['form', 'status'], name='forms_forms_form_id_08589c_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['form', 'submitted_at'], name='forms_forms_form_id_8bb17e_idx'),
        ),
        migrations.AddIndex(
            model_name='formsubmissionvalue',
            index=models.Index(fields=['submission', 'field_key'], name='forms_forms_submiss_69db05_idx'),
        ),
    ]
