# Generated by Django 6.0.2 on 2026-09-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field_key',
            field=models.CharField(blank=True, db_index=True, help_text='Stable internal key for system fields', max_length=60, null=True),
        ),
    ]
