# Generated by Django 6.0.2 on 2026-09-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_formfield_field_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formassignment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='formassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('target',), name='unique_active_assignment_per_target'),
        ),
    ]
