# Generated by Django 6.0.2 on 2026-07-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('content_manager', 'Content Manager'), ('editor', 'Editor'), ('marketing_manager', 'Marketing Manager'), ('marketing_seo', 'Marketing / SEO'), ('recruiter', 'Recruiter'), ('support_agent', 'Support Agent'), ('support_recruiter', 'Support / Recruiter'), ('lms_admin', 'LMS Admin'), ('finance_sales', 'Finance / Sales')], default='content_manager', help_text="Determines the user's default permissions inside the CMS.", max_length=32),
        ),
    ]
