# Generated by Django 6.0.2 on 2026-07-10 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('name_ar', models.CharField(blank=True, max_length=255, verbose_name='Name (Arabic)')),
                ('slug', models.SlugField(help_text='URL-safe identifier.', max_length=255, unique=True, verbose_name='Slug')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (Arabic)')),
                ('website_url', models.URLField(blank=True, verbose_name='Website URL')),
                ('open_in_new_tab', models.BooleanField(default=True, verbose_name='Open in new tab')),
                ('partner_type', models.CharField(choices=[('client', 'Client'), ('strategic_partner', 'Strategic Partner'), ('academic_partner', 'Academic Partner'), ('technology_partner', 'Technology Partner'), ('training_partner', 'Training Partner'), ('other', 'Other')], default='client', max_length=32, verbose_name='Partner type')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower values appear first.', verbose_name='Display order')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive partners are hidden from public APIs.', verbose_name='Active')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediaasset', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'db_table': 'partners_partner',
                'ordering': ['display_order', 'name_en'],
                'indexes': [models.Index(fields=['partner_type', 'is_active', 'display_order', 'name_en'], name='partners_type_active_order_idx'), models.Index(fields=['is_featured', 'is_active', 'display_order'], name='partners_featured_order_idx')],
            },
        ),
    ]
