# Generated by Django 5.2.16 on 2026-07-09 17:43

import apps.media_library.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to=apps.media_library.models.media_file_path)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], default='other', max_length=32)),
                ('usage_context', models.CharField(blank=True, help_text='Where this asset is intended to be used, e.g. partner logo.', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Media Asset',
                'verbose_name_plural': 'Media Assets',
                'db_table': 'media_library_mediaasset',
                'ordering': ['-created_at'],
            },
        ),
    ]
